### ISSUE TITLE
Figwheel seems not to work with .cljc libraries

### ISSUE THREAD

**Issue by alexandergunnarson** [bhauman/lein-figwheel#129]
First of all, I'd really like to express my appreciation for this project. Figwheel is extremely useful and I use it all the time for ClojureScript development. Thanks for all your hard work!

I recently (as of today) deployed an almost entirely .cljc-based library, ```lein install```ing it, etc., and launched Figwheel to make sure it compiled in ClojureScript (all my Clojure tests ran fine). I used to use cljx, but I found it was somewhat unwieldy compared to the new cljc format with reader conditionals. So, presumably because I no longer have .clj files for the macros and am only using .cljc files, I get a "WARNING: Use of undeclared Var quantum.core.ns/defmacro" when trying to load ns.cljc, which I never got before when using cljx. Is this a ClojureScript issue or is this a Figwheel issue?

Here's my project.clj for your convenience. The ```quantum/core``` dependency is what's causing issues:

```
(defproject ramsey "1.0.0-SNAPSHOT"
  :description "Clojure web app for virtual envelopes"
  :jvm-opts    []
  :url         "http://ramsey.herokuapp.com"
  :license
    {:name "Eclipse Public License v1.0"
     :url  "http://www.eclipse.org/legal/epl-v10.html"}
  :main  ramsey.web
  :repositories {"sonatype-oss-public"
               "https://oss.sonatype.org/content/groups/public/"}
  :dependencies
    [; ==== CLOJURE ====
     [org.clojure/clojure       "1.7.0-beta1"  ]
     [fast-zip "0.6.1"]
     ;[org.clojure/data.xml      "0.0.8"]
     [com.github.detro.ghostdriver/phantomjsdriver "1.1.0"]
     [fx-clj                    "0.2.0-alpha1"  ]
     [freactive.core            "0.2.0-alpha1"  ]
     [into-edn "1.0.2"]
     ; ==== SERVER ====
     [compojure                 "1.1.8"         ]
     [ring/ring-jetty-adapter   "1.2.2"         ]
     [environ                   "0.5.0"         ]
     ;[com.cemerick/drawbridge   "0.0.6"         ]
     ; ==== QUANTUM ====
     [quantum/core              "0.2.3.0"       ] ; "0.2.0.0" stable // 0.2.2.0 cljx // 0.2.3.0 latest
     ; ==== TEMP ====
     [org.clojure/core.async    "0.1.346.0-17112a-alpha"]
     ; ==== CLOJURESCRIPT ====  
     [org.clojure/clojurescript "0.0-3196"      ]
     [reagent                   "0.5.0"         ]
     [freactive                 "0.1.0"         ] ; a pure ClojureScript answer to react + reagent
     [figwheel                  "0.2.6"         ]
     [garden                    "1.2.5"         ]
     ;[domina                    "1.0.3"         ] ; DOM manipulation
     [cljs-http                 "0.1.27"        ]] 
  :min-lein-version "2.0.0"
  :plugins
    [[environ/environ.lein "0.2.1"]  ; what does this mean??
     ;[lein-cljsbuild       "1.0.5"]
     ;[com.keminglabs/cljx "0.6.0"]
     [lein-cljsbuild "1.0.4"] ; A requirement for figwheel?
     [lein-figwheel "0.2.6"]]
  ;:prep-tasks   [["cljx" "once"] "javac" "compile"] ; javac compile makes it all AOT though right...?
  :source-paths ["src/clj" "src/cljs" "src/cljc"]
   :uberjar {:aot :all}
  :auto-clean false ; because of https://github.com/weavejester/lein-ring/issues/126
  :cljsbuild
    {:builds
      [{:id "ramsey"
        :source-paths ["src/cljs"]
        :compiler
          {:output-to            "resources/public/js/ramsey.js"
           :output-dir           "resources/public/js/out"
           :optimizations        :none ; CHANGE THIS to :advanced
           :cache-analysis       true
           :source-map-timestamp true
           :source-map           true}}]}
  :figwheel
    {:css-dirs          ["resources/public/css"]
     :open-file-command "emacsclient"}
  :hooks [environ.leiningen.hooks]          ; what does this mean??
  :uberjar-name "ramsey-standalone.jar"
  :profiles
    {:dev
      {:dependencies
        [[org.clojure/tools.nrepl     "0.2.7" ]
         [com.cemerick/piggieback     "0.1.5" ]
         [org.clojure/tools.namespace "0.2.11-SNAPSHOT"]]
       :plugins 
         [[com.cemerick/austin     "0.1.6"]
          [com.cemerick/piggieback "0.1.5"]
          ;[com.keminglabs/cljx     "0.6.0"]
          ]
       ; :injections
       ;    [(do (ns quanta.main)
       ;         (require '[quantum.core.ns :as ns :refer :all])
       ;         (ns/require-all *ns* :clj :lib)
       ;         (log/enable! :debug :inspect :warn)
       ;         ;(in-ns ramsey.web)
       ;         (clojure.main/repl :print !))]
       :repl-options
         {:nrepl-middleware
           [cemerick.piggieback/wrap-cljs-repl]}}
     :production {:env {:production true}}}) ; what does this mean??
```

**Comment by bhauman** [comment]
.cljc support in figwheel has just been added and is currently in the 0.2.7-SNAPSHOT release.

**Comment by alexandergunnarson** [comment]
Well that was fast! Thanks so much for your quick response.

**Comment by alexandergunnarson** [comment]
I may be doing something wrong, but I get a "WARNING: Required namespace not provided for figwheel.client" when loading the following simple namespace (the only namespace in my project currently, as I temporarily cleaned it out to test):

```
(ns ramsey.core
  (:require
    [figwheel.client :as fw :include-macros true]
    [cljs.core.async :refer [<! chan sliding-buffer put! close! timeout]])
  (:require-macros
    [cljs.core.async.macros :refer [go-loop go]]))
; [quantum.core.ns]
(enable-console-print!)

(defn init! []
  (println "Hi!"))

(fw/watch-and-reload
  :websocket-url "ws://localhost:3449/figwheel-ws"
  :jsload-callback (fn [] (init!)))
```

If I take out the figwheel-related ```require``` and the associated function (```watch-and-reload```), figwheel loads fine but doesn't auto-reload.

**Comment by bhauman** [comment]
Does this work with cljsbuild? lein cljsbuild once?

Can you create a minimal example perhaps with lein figwheel new as a
starting point?

**Comment by alexandergunnarson** [comment]
I tried ```lein cljsbuild once``` and here's the output:

```WARNING: Required namespace not provided for figwheel.client
Successfully compiled "resources/public/js/ramsey.js" in 1.46 seconds.```

So it seems to be an issue with cljsbuild or possibly some dependency conflict. I'm going to try with just ```lein figwheel new``` and see if it compiles from there.

**Comment by alexandergunnarson** [comment]
I created a new test project with only a project.clj and ran ```lein figwheel new```. The project.clj looks like this:

```
(defproject test-app "0.0.1-SNAPSHOT"
  :description "Test app"
  :jvm-opts    []
  :url         "http://myapp.herokuapp.com"
  :license
    {:name "Eclipse Public License v1.0"
     :url  "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies
    [; ==== CLOJURE ====
     [org.clojure/clojure       "1.7.0-beta1"  ]
     [org.clojure/clojurescript "0.0-3196"      ]
     [lein-figwheel "0.2.7-SNAPSHOT"]] 
  :plugins
    [[lein-cljsbuild "1.0.5"] ; Required for figwheel
     [lein-figwheel "0.2.7-SNAPSHOT"]]
  :source-paths ["src/clj" "src/cljs" "src/cljc"]
  :auto-clean false ; because of https://github.com/weavejester/lein-ring/issues/126
  :cljsbuild
    {:builds
      [{:id "test-app"
        :source-paths ["src/cljs"]
        :compiler
          {:output-to            "resources/public/js/ramsey.js"
           :output-dir           "resources/public/js/out"
           :optimizations        :none ; CHANGE THIS to :advanced
           :cache-analysis       true
           :source-map-timestamp true
           :source-map           true}}]}
  :figwheel
    {:css-dirs          ["resources/public/css"]})
```

```lein figwheel new``` outputs the following:
"Figwheel: No cljsbuild specified. You may have mistyped the build id on the command line or failed to specify a build in the :cljsbuild section of your project.clj. You need to have at least one build with :optimizations set to :none."

**Comment by alexandergunnarson** [comment]
I created a new file called "core.cljs" in /src/cljs/test_app/ like so:

```
(ns test-app.core
  (:require
    [figwheel.client :as fw]))
```

and ran ```lein cljsbuild once```. The output is the following:

```
Alexanders-MacBook-Pro-5:test-app alexandergunnarson$ lein cljsbuild once
Compiling ClojureScript.
Compiling "resources/public/js/test-app.js" from ["src/cljs"]...
Compiling "resources/public/js/test-app.js" failed.
clojure.lang.ExceptionInfo: failed compiling file:src/cljs/test_app/core.cljs {:file #object[java.io.File 0x49a06087 "src/cljs/test_app/core.cljs"]}
	at clojure.core$ex_info.invoke(core.clj:4591)
	at cljs.compiler$compile_file$fn__3066.invoke(compiler.clj:1140)
	at cljs.compiler$compile_file.invoke(compiler.clj:1105)
	at cljs.compiler$compile_root.invoke(compiler.clj:1175)
	at cljs.closure$compile_dir.invoke(closure.clj:369)
	at cljs.closure$eval3392$fn__3393.invoke(closure.clj:409)
	at cljs.closure$eval3345$fn__3346$G__3336__3353.invoke(closure.clj:316)
	at cljs.closure$eval3405$fn__3406.invoke(closure.clj:423)
	at cljs.closure$eval3345$fn__3346$G__3336__3353.invoke(closure.clj:316)
	at cljsbuild.compiler.SourcePaths$fn__3780.invoke(compiler.clj:67)
	at clojure.core$map$fn__4532.invoke(core.clj:2620)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:507)
	at clojure.core$seq__4107.invoke(core.clj:135)
	at clojure.core$apply.invoke(core.clj:628)
	at clojure.core$mapcat.doInvoke(core.clj:2658)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at cljsbuild.compiler.SourcePaths._compile(compiler.clj:67)
	at cljs.closure$build.invoke(closure.clj:1437)
	at cljs.closure$build.invoke(closure.clj:1392)
	at cljsbuild.compiler$compile_cljs$fn__3791.invoke(compiler.clj:81)
	at cljsbuild.compiler$compile_cljs.invoke(compiler.clj:80)
	at cljsbuild.compiler$run_compiler.invoke(compiler.clj:180)
	at user$eval3923$iter__3959__3963$fn__3964$fn__3982.invoke(form-init2496630620495761832.clj:1)
	at user$eval3923$iter__3959__3963$fn__3964.invoke(form-init2496630620495761832.clj:1)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:507)
	at clojure.core$seq__4107.invoke(core.clj:135)
	at clojure.core$dorun.invoke(core.clj:3007)
	at clojure.core$doall.invoke(core.clj:3023)
	at user$eval3923.invoke(form-init2496630620495761832.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6792)
	at clojure.lang.Compiler.eval(Compiler.java:6782)
	at clojure.lang.Compiler.load(Compiler.java:7237)
	at clojure.lang.Compiler.loadFile(Compiler.java:7175)
	at clojure.main$load_script.invoke(main.clj:275)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invoke(main.clj:308)
	at clojure.main$null_opt.invoke(main.clj:343)
	at clojure.main$main.doInvoke(main.clj:421)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: clojure.lang.ExceptionInfo: No such namespace: figwheel.client, could not locate figwheel/client.cljs or figwheel/client.cljc at line 1 src/cljs/test_app/core.cljs {:file "src/cljs/test_app/core.cljs", :line 1, :column 1, :tag :cljs/analysis-error}
	at clojure.core$ex_info.invoke(core.clj:4591)
	at cljs.analyzer$error.invoke(analyzer.clj:378)
	at cljs.analyzer$error.invoke(analyzer.clj:376)
	at cljs.analyzer$analyze_deps.invoke(analyzer.clj:1263)
	at cljs.analyzer$eval1709$fn__1711.invoke(analyzer.clj:1515)
	at clojure.lang.MultiFn.invoke(MultiFn.java:251)
	at cljs.analyzer$analyze_seq.invoke(analyzer.clj:1858)
	at cljs.analyzer$analyze$fn__1945.invoke(analyzer.clj:1950)
	at cljs.analyzer$analyze.invoke(analyzer.clj:1943)
	at cljs.compiler$compile_file_STAR_$fn__3034.invoke(compiler.clj:1023)
	at cljs.compiler$with_core_cljs.invoke(compiler.clj:964)
	at cljs.compiler$compile_file_STAR_.invoke(compiler.clj:984)
	at cljs.compiler$compile_file$fn__3066.invoke(compiler.clj:1123)
	... 45 more
Subprocess failed
```

**Comment by alexandergunnarson** [comment]
It compiles fine with ```lein new figwheel hello-world```. I even changed the dependency from the default "0.2.5-SNAPSHOT" to "0.2.7-SNAPSHOT", and the ClojureScript dependency from the default "0.0-2850" to "0.0-3196", as well as the lein-cljsbuild dependency from "1.0.4" to "1.0.5". I'm not quite sure yet what the issue was, but it may have been with my cljsbuild profile. I'm trying now to copy basically everything over from the lein new figwheel generated project.clj to my original project.clj in the project that was having problems. I'll let you know what happens.

**Comment by alexandergunnarson** [comment]
It could have been other things, but I think the main problem must have been that I was using lein-figwheel instead of just figwheel as a dependency. A dumb mistake, but it happens, I suppose :/

**Comment by bhauman** [comment]
Alright,

This makes sense you are not requiring the figwheel client which is a separate library.

Remove [lein-figwheel 0.2.7 ...] from :dependencies and add [figwheel 0.2.7-SNAPSHOT]

**Comment by bhauman** [comment]
Oh I  see you found it. 

Yeah I wish it was simpler. But there's a reason for the separate libs.

**Comment by lvh** [comment]
@bhauman: are you supposed to have both of those dependencies? Is that documented? I too, only had the lein plugin.

**Comment by bhauman** [comment]
You only need the plugin for the latest figwheel.
