### ISSUE TITLE
Error with foreign clojurescript dependency

### ISSUE THREAD

**Issue by ducky427** [bhauman/lein-figwheel#147]
Hello,
I am using lein-figwheel v0.3.1 with ClojureScript 0.0-3211.

I have defined a clojurescript external/foreign javascript dependency file as described on [cljs wiki](https://github.com/clojure/clojurescript/wiki/Foreign-Dependencies). However when I run, `lein figwheel`, I get the following error:

```
Exception in thread "main" java.lang.AssertionError: No ns form found in src/cljs/deps.cljs, compiling:(/private/var/folders/4b/9kykjxk974qccq31ckq26nbm0000gp/T/form-init7986036336730204132.clj:1:125)
	at clojure.lang.Compiler.load(Compiler.java:7249)
	at clojure.lang.Compiler.loadFile(Compiler.java:7175)
	at clojure.main$load_script.invoke(main.clj:275)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invoke(main.clj:308)
	at clojure.main$null_opt.invoke(main.clj:343)
	at clojure.main$main.doInvoke(main.clj:421)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.lang.AssertionError: No ns form found in src/cljs/deps.cljs
	at cljs.analyzer$parse_ns$fn__2136.invoke(analyzer.clj:2095)
	at cljs.analyzer$parse_ns.invoke(analyzer.clj:2055)
	at cljs.analyzer$parse_ns.invoke(analyzer.clj:2046)
	at cljs.analyzer$analyze_file.invoke(analyzer.clj:2170)
	at figwheel_sidecar.repl$analyze_build.invoke(repl.clj:249)
	at figwheel_sidecar.repl$analyze_builds.invoke(repl.clj:254)
	at figwheel_sidecar.repl$run_autobuilder_helper.invoke(repl.clj:288)
	at figwheel_sidecar.repl$start_autobuild.invoke(repl.clj:359)
	at figwheel_sidecar.repl$run_autobuilder.invoke(repl.clj:517)
	at user$eval21994.invoke(form-init7986036336730204132.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6792)
	at clojure.lang.Compiler.eval(Compiler.java:6782)
	at clojure.lang.Compiler.load(Compiler.java:7237)
	... 11 more
```

I have tried updating to the latest cljs as well to no effect.

Any help would be greatly appreciated.

Thanks!

**Comment by bhauman** [comment]
Yep, this is a bug in Figwheel.  Thanks for the report.

**Comment by ducky427** [comment]
Thanks @bhauman!

**Comment by ducky427** [comment]
Thanks a lot @bhauman! really appreciated.

Is it possible to do a snapshot release?

**Comment by bhauman** [comment]
0.3.2-SNAPSHOT deployed

**Comment by ducky427** [comment]
Thats great. Thanks a ton @bhauman!! Trying to get figwheel working with my atom-shell app.

**Comment by minikomi** [comment]
Ah thanks @bhauman & @ducky427 for pointing it out
