### ISSUE TITLE
Figwheel doesn't work with versions of CLJS > 3211

### ISSUE THREAD

**Issue by ultimapanzer** [bhauman/lein-figwheel#152]
I updated my deps today, and got this error:

```
Exception in thread "main" java.io.FileNotFoundException: Could not locate cljs/repl__init.class or cljs/repl.clj on classpath: , compiling:(figwheel_sidecar/repl.clj:1:1)
	at clojure.lang.Compiler.load(Compiler.java:7142)
	at clojure.lang.RT.loadResourceScript(RT.java:370)
	at clojure.lang.RT.loadResourceScript(RT.java:361)
	at clojure.lang.RT.load(RT.java:440)
	at clojure.lang.RT.load(RT.java:411)
	at clojure.core$load$fn__5066.invoke(core.clj:5641)
	at clojure.core$load.doInvoke(core.clj:5640)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5446)
	at clojure.core$load_lib$fn__5015.invoke(core.clj:5486)
	at clojure.core$load_lib.doInvoke(core.clj:5485)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:626)
	at clojure.core$load_libs.doInvoke(core.clj:5524)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:626)
	at clojure.core$require.doInvoke(core.clj:5607)
	at clojure.lang.RestFn.invoke(RestFn.java:436)
	at user$eval5.invoke(form-init7199843789878254382.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6703)
	at clojure.lang.Compiler.eval(Compiler.java:6692)
	at clojure.lang.Compiler.load(Compiler.java:7130)
	at clojure.lang.Compiler.loadFile(Compiler.java:7086)
	at clojure.main$load_script.invoke(main.clj:274)
	at clojure.main$init_opt.invoke(main.clj:279)
	at clojure.main$initialize.invoke(main.clj:307)
	at clojure.main$null_opt.invoke(main.clj:342)
	at clojure.main$main.doInvoke(main.clj:420)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.io.FileNotFoundException: Could not locate cljs/repl__init.class or cljs/repl.clj on classpath:
	at clojure.lang.RT.load(RT.java:443)
	at clojure.lang.RT.load(RT.java:411)
	at clojure.core$load$fn__5066.invoke(core.clj:5641)
	at clojure.core$load.doInvoke(core.clj:5640)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5446)
	at clojure.core$load_lib$fn__5015.invoke(core.clj:5486)
	at clojure.core$load_lib.doInvoke(core.clj:5485)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:626)
	at clojure.core$load_libs.doInvoke(core.clj:5524)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:626)
	at clojure.core$require.doInvoke(core.clj:5607)
	at clojure.lang.RestFn.invoke(RestFn.java:3659)
	at figwheel_sidecar.repl$eval65$loading__4958__auto____66.invoke(repl.clj:1)
	at figwheel_sidecar.repl$eval65.invoke(repl.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6703)
	at clojure.lang.Compiler.eval(Compiler.java:6692)
	at clojure.lang.Compiler.load(Compiler.java:7130)
	... 32 more
```

Tried walking the CLJS version back down to 3211, and none of the versions > 3211 worked.

**Comment by bhauman** [comment]
I tested this on 3255 and 3269 and both work fine.  When you change dependencies in Clojure it is very important to do a `lein clean`.

**Comment by annapawlicka** [comment]
I'm experiencing the same problem despite doing `lein clean` and confirming that all files have been deleted. Using cljs `3269` and figwheel `0.3.1` (with and without cider-nrepl in exclusions).

**Comment by bensu** [comment]
What Clojure version are you using? cljs  > 3211 requires clj > 1.7 since `cljs.repl` is now in a .cljc file.

**Comment by annapawlicka** [comment]
@bensu Ha! My bad, I was on 1.6, upgrading Clojure to `1.7.0-beta3` fixed the problem. Thanks!

**Comment by geraldodev** [comment]
I envy you fellows :(

Following Quick start 
```
(defproject ola "0.1.0-SNAPSHOT"
  :dependencies [[org.clojure/clojure "1.7.0-beta2"]
                 [org.clojure/clojurescript "0.0-3269"]
                 ]
  :plugins [[lein-cljsbuild "1.0.6"]
            [lein-figwheel "0.3.2-SNAPSHOT"]]
  :clean-targets ^{:protect false} [:target-path "out"]
  :cljsbuild {
    :builds [{:id "dev"
              :source-paths ["src"]
              :figwheel true
              :compiler {:main ola.core}
             }]
   })
```

```
Figwheel: focusing on build-ids (dev)
Compiling "main.js" from ["src"]...
Compiling "main.js" failed.
clojure.lang.ExceptionInfo: failed compiling file:target/figwheel_temp/dev/figwheel/connect.cljs
 at clojure.core$ex_info.invoke (core.clj:4591)
    cljs.compiler$compile_file$fn__3059.invoke (compiler.cljc:1146)
    cljs.compiler$compile_file.invoke (compiler.cljc:1109)
    cljs.compiler$compile_root.invoke (compiler.cljc:1181)
    cljs.closure$compile_dir.invoke (closure.clj:384)
    cljs.closure$eval3462$fn__3463.invoke (closure.clj:424)
    cljs.closure$eval3415$fn__3416$G__3406__3423.invoke (closure.clj:331)
    cljs.closure$eval3475$fn__3476.invoke (closure.clj:438)
    cljs.closure$eval3415$fn__3416$G__3406__3423.invoke (closure.clj:331)
    clojurescript_build.core.CompilableSourcePaths/fn (core.clj:19)
    clojure.core$map$fn__4550.invoke (core.clj:2620)
    clojure.lang.LazySeq.sval (LazySeq.java:40)
    clojure.lang.LazySeq.seq (LazySeq.java:49)
    clojure.lang.RT.seq (RT.java:507)
    clojure.core/seq (core.clj:135)
    clojure.core$apply.invoke (core.clj:628)
    clojure.core$mapcat.doInvoke (core.clj:2658)
    clojure.lang.RestFn.invoke (RestFn.java:423)
    clojurescript_build.core.CompilableSourcePaths._compile (core.clj:19)
    cljs.closure$build.invoke (closure.clj:1471)
    clojurescript_build.core$build_source_paths_STAR_.invoke (core.clj:153)
    figwheel_sidecar.auto_builder$default_build_options$fn__17585.invoke (auto_builder.clj:77)
    figwheel_sidecar.auto_builder$insert_figwheel_connect_script$fn__17618.invoke (auto_builder.clj:178)
    figwheel_sidecar.auto_builder$warning$fn__17582.invoke (auto_builder.clj:73)
    clojurescript_build.auto$time_build$fn__17378.invoke (auto.clj:55)
    clojurescript_build.auto$after$fn__17384.invoke (auto.clj:64)
    clojurescript_build.auto$after$fn__17384.invoke (auto.clj:64)
    clojurescript_build.auto$after$fn__17384.invoke (auto.clj:64)
    clojurescript_build.auto$error$fn__17387.invoke (auto.clj:71)
    clojurescript_build.auto$before$fn__17381.invoke (auto.clj:60)
```

With 0.3.1 I have the same problem.

**Comment by geraldodev** [comment]
Sorry, bogus error. Giving another stab on cljs.
Figwheel is a necessity.
