### ISSUE TITLE
lein figwheel

### ISSUE THREAD

**Issue by bantyg** [bhauman/lein-figwheel#168]
Hi,
I have an issue with 'lein-figwheel'.I have one project when I am running command 'lein figwheel' its shows error.

Exception in thread "main" java.util.regex.PatternSyntaxException: Unknown inline modifier near index 2
(?U)^[\p{Alpha}_$]
  ^, compiling:(cljs/util.cljc:159:33)

When I am doing lein new ,its working fine.I am not able to find it out..... why its happening..

**Comment by bhauman** [comment]
I need some more info. 

What OS are you running and can you send me your project.clj?

**Comment by bantyg** [comment]
(defproject featured-links "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}

  :source-paths ["src/clj" "src/cljs"]

  :dependencies [[org.clojure/clojure "1.7.0-beta3"]
                 [ring-server "0.4.0"]
                 [cljsjs/react "0.13.1-0"]
                 [reagent "0.5.0"]
                 [reagent-forms "0.5.1"]
                 [reagent-utils "0.1.4"]
                 [ring "1.3.2"]
                 [ring/ring-defaults "0.1.4"]
                 [prone "0.8.2"]
                 [compojure "1.3.3"]
                 [hiccup "1.0.5"]
                 [environ "1.0.0"]
                 [org.clojure/clojurescript "0.0-3291" :scope "provided"]
                 [secretary "1.2.3"]]

  :plugins [[lein-ring "0.9.1"]
            [lein-environ "1.0.0"]
            [lein-asset-minifier "0.2.2"]]

  :ring {:handler featured-links.handler/app
         :uberwar-name "featured-links.war"}

  :min-lein-version "2.5.0"

  :uberjar-name "featured-links.jar"

  :main featured-links.server

  :clean-targets ^{:protect false} [[:cljsbuild :builds :app :compiler :output-dir]
                                    [:cljsbuild :builds :app :compiler :output-to]]

  :minify-assets
  {:assets
    {"resources/public/css/site.min.css" "resources/public/css/site.css"}}

  :cljsbuild {:builds {:app {:source-paths ["src/cljs"]
                             :compiler {:output-to     "resources/public/js/app.js"
                                        :output-dir    "resources/public/js/out"
                                        :asset-path   "js/out"
                                        :optimizations :none
                                        :pretty-print  true}}}}

  :profiles {:dev {:repl-options {:init-ns featured-links.repl
                                  :nrepl-middleware [cemerick.piggieback/wrap-cljs-repl]}

                   :dependencies [[ring-mock "0.1.5"]
                                  [ring/ring-devel "1.3.2"]
                                  [weasel "0.6.0"]
                                  [leiningen-core "2.5.1"]
                                  [lein-figwheel "0.3.3"]
                                  [com.cemerick/piggieback "0.2.1"]
                                  [org.clojure/tools.nrepl "0.2.10"]
                                  [pjstadig/humane-test-output "0.7.0"]]

                   :source-paths ["env/dev/clj"]
                   :plugins [[lein-figwheel "0.3.3"]
                             [lein-cljsbuild "1.0.6"]
                             [com.cemerick/clojurescript.test "0.3.2"]]

                   :injections [(require 'pjstadig.humane-test-output)
                                (pjstadig.humane-test-output/activate!)]

                   :figwheel {:http-server-root "public"
                              :server-port 3449
                              :css-dirs ["resources/public/css"]
                              :ring-handler featured-links.handler/app}

                   :env {:dev true}

                   :cljsbuild {:builds {:app {:source-paths ["env/dev/cljs"]
                                              :compiler {:main "featured-links.dev"
                                                         :source-map true}}
                                        :test {:source-paths ["src/cljs"  "test/cljs"]
                                               :compiler {:output-to "target/test.js"
                                                          :optimizations :whitespace
                                                          :pretty-print true}}}
                               :test-commands {"unit" ["phantomjs" :runner
                                                       "test/vendor/es5-shim.js"
                                                       "test/vendor/es5-sham.js"
                                                       "test/vendor/console-polyfill.js"
                                                       "target/test.js"]}}}

             :uberjar {:hooks [leiningen.cljsbuild minify-assets.plugin/hooks]
                       :env {:production true}
                       :aot :all
                       :omit-source true
                       :cljsbuild {:jar true
                                   :builds {:app
                                             {:source-paths ["env/prod/cljs"]
                                              :compiler
                                              {:optimizations :advanced
                                               :pretty-print false}}}}}})


This is my project.clj and I am using mac OS X

**Comment by bhauman** [comment]
Hmmm does this work with cljsbuild?

**Comment by ivanbokii** [comment]
Having the same issue here.
Was trying to go through om tutorial and did this:
`lein new figwheel om-tut -- --om` and then `lein figwheel` from the om-tut directory

```clojure
(defproject om-tut "0.1.0-SNAPSHOT"
  :description "FIXME: write this!"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}

  :dependencies [[org.clojure/clojure "1.6.0"]
                 [org.clojure/clojurescript "0.0-3211"]
                 [org.clojure/core.async "0.1.346.0-17112a-alpha"]
                 [sablono "0.3.4"]
                 [org.omcljs/om "0.8.8"]]

  :plugins [[lein-cljsbuild "1.0.5"]
            [lein-figwheel "0.3.1"]]

  :source-paths ["src"]

  :clean-targets ^{:protect false} ["resources/public/js/compiled" "target"]
  
  :cljsbuild {
    :builds [{:id "dev"
              :source-paths ["src"]

              :figwheel { :on-jsload "om-tut.core/on-js-reload" }

              :compiler {:main om-tut.core
                         :asset-path "js/compiled/out"
                         :output-to "resources/public/js/compiled/om_tut.js"
                         :output-dir "resources/public/js/compiled/out"
                         :source-map-timestamp true }}
             {:id "min"
              :source-paths ["src"]
              :compiler {:output-to "resources/public/js/compiled/om_tut.js"
                         :main om-tut.core                         
                         :optimizations :advanced
                         :pretty-print false}}]}

  :figwheel {
             ;; :http-server-root "public" ;; default and assumes "resources" 
             ;; :server-port 3449 ;; default
             :css-dirs ["resources/public/css"] ;; watch and update CSS

             ;; Start an nREPL server into the running figwheel process
             ;; :nrepl-port 7888

             ;; Server Ring Handler (optional)
             ;; if you want to embed a ring handler into the figwheel http-kit
             ;; server, this is for simple ring servers, if this
             ;; doesn't work for you just run your own server :)
             ;; :ring-handler hello_world.server/handler

             ;; To be able to open files in your editor from the heads up display
             ;; you will need to put a script on your path.
             ;; that script will have to take a file path and a line number
             ;; ie. in  ~/bin/myfile-opener
             ;; #! /bin/sh
             ;; emacsclient -n +$2 $1
             ;;
             ;; :open-file-command "myfile-opener"

             ;; if you want to disable the REPL
             ;; :repl false

             ;; to configure a different figwheel logfile path
             ;; :server-logfile "tmp/logs/figwheel-logfile.log" 
             })
```

**Comment by bhauman** [comment]
Please check or remove your `~/.lein/profiles.clj`.

I just ran this command on my machine and it seems to work here.

@ivanbokii Are you getting the same Regex error?

**Comment by bhauman** [comment]
@bantyg Can you get me a longer stacktrace?

**Comment by bantyg** [comment]
I have removed that file but still I am getting same error

**Comment by bantyg** [comment]
Exception in thread "main" java.util.regex.PatternSyntaxException: Unknown inline modifier near index 2
(?U)^[\p{Alpha}_$]
  ^, compiling:(cljs/util.cljc:159:33)
        at clojure.lang.Compiler.load(Compiler.java:7244)
        at clojure.lang.RT.loadResourceScript(RT.java:371)
        at clojure.lang.RT.loadResourceScript(RT.java:362)
        at clojure.lang.RT.load(RT.java:446)
        at clojure.lang.RT.load(RT.java:412)
        at clojure.core$load$fn__5446.invoke(core.clj:5862)
        at clojure.core$load.doInvoke(core.clj:5861)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invoke(core.clj:5667)
        at clojure.core$load_lib$fn__5395.invoke(core.clj:5707)
        at clojure.core$load_lib.doInvoke(core.clj:5706)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invoke(core.clj:630)
        at clojure.core$load_libs.doInvoke(core.clj:5745)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invoke(core.clj:630)
        at clojure.core$require.doInvoke(core.clj:5828)
        at clojure.lang.RestFn.invoke(RestFn.java:2088)
        at cljs.repl$eval71$loading__5338__auto____72.invoke(repl.cljc:9)
        at cljs.repl$eval71.invoke(repl.cljc:9)
        at clojure.lang.Compiler.eval(Compiler.java:6792)
        at clojure.lang.Compiler.eval(Compiler.java:6781)
        at clojure.lang.Compiler.load(Compiler.java:7237)
        at clojure.lang.RT.loadResourceScript(RT.java:371)
        at clojure.lang.RT.loadResourceScript(RT.java:362)
        at clojure.lang.RT.load(RT.java:446)
        at clojure.lang.RT.load(RT.java:412)
        at clojure.core$load$fn__5446.invoke(core.clj:5862)
        at clojure.core$load.doInvoke(core.clj:5861)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invoke(core.clj:5667)
        at clojure.core$load_lib$fn__5395.invoke(core.clj:5707)
        at clojure.core$load_lib.doInvoke(core.clj:5706)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invoke(core.clj:630)
        at clojure.core$load_libs.doInvoke(core.clj:5745)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invoke(core.clj:630)
        at clojure.core$require.doInvoke(core.clj:5828)
        at clojure.lang.RestFn.invoke(RestFn.java:3659)
        at figwheel_sidecar.repl$eval65$loading__5338__auto____66.invoke(repl.clj:1)
        at figwheel_sidecar.repl$eval65.invoke(repl.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6792)
        at clojure.lang.Compiler.eval(Compiler.java:6781)
        at clojure.lang.Compiler.load(Compiler.java:7237)
        at clojure.lang.RT.loadResourceScript(RT.java:371)
        at clojure.lang.RT.loadResourceScript(RT.java:362)
        at clojure.lang.RT.load(RT.java:446)
        at clojure.lang.RT.load(RT.java:412)
        at clojure.core$load$fn__5446.invoke(core.clj:5862)
        at clojure.core$load.doInvoke(core.clj:5861)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invoke(core.clj:5667)
        at clojure.core$load_lib$fn__5395.invoke(core.clj:5707)
        at clojure.core$load_lib.doInvoke(core.clj:5706)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invoke(core.clj:630)
        at clojure.core$load_libs.doInvoke(core.clj:5745)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invoke(core.clj:630)
        at clojure.core$require.doInvoke(core.clj:5828)
        at clojure.lang.RestFn.invoke(RestFn.java:436)
        at user$eval5.invoke(form-init3477988297509233361.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6792)
        at clojure.lang.Compiler.eval(Compiler.java:6781)
        at clojure.lang.Compiler.load(Compiler.java:7237)
        at clojure.lang.Compiler.loadFile(Compiler.java:7175)
        at clojure.main$load_script.invoke(main.clj:275)
        at clojure.main$init_opt.invoke(main.clj:280)
        at clojure.main$initialize.invoke(main.clj:308)
        at clojure.main$null_opt.invoke(main.clj:343)
        at clojure.main$main.doInvoke(main.clj:421)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at clojure.lang.Var.invoke(Var.java:383)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.Var.applyTo(Var.java:700)
        at clojure.main.main(main.java:37)
Caused by: java.util.regex.PatternSyntaxException: Unknown inline modifier near index 2
(?U)^[\p{Alpha}_$]
  ^
        at java.util.regex.Pattern.error(Pattern.java:1713)
        at java.util.regex.Pattern.group0(Pattern.java:2519)
        at java.util.regex.Pattern.sequence(Pattern.java:1806)
        at java.util.regex.Pattern.expr(Pattern.java:1752)
        at java.util.regex.Pattern.compile(Pattern.java:1460)
        at java.util.regex.Pattern.<init>(Pattern.java:1133)
        at java.util.regex.Pattern.compile(Pattern.java:823)
        at clojure.lang.LispReader$RegexReader.invoke(LispReader.java:505)
        at clojure.lang.LispReader$DispatchReader.invoke(LispReader.java:682)
        at clojure.lang.LispReader.read(LispReader.java:255)
        at clojure.lang.LispReader.readDelimitedList(LispReader.java:1189)
        at clojure.lang.LispReader$ListReader.invoke(LispReader.java:1038)
        at clojure.lang.LispReader.read(LispReader.java:255)
        at clojure.lang.LispReader.readDelimitedList(LispReader.java:1189)
        at clojure.lang.LispReader$ListReader.invoke(LispReader.java:1038)
        at clojure.lang.LispReader.read(LispReader.java:255)
        at clojure.lang.LispReader.read(LispReader.java:195)
        at clojure.lang.Compiler.load(Compiler.java:7232)
        ... 76 more
Subprocess failed
IN-5:featured-links-tile poojag$ lein figwheel
Exception in thread "main" java.util.regex.PatternSyntaxException: Unknown inline modifier near index 2
(?U)^[\p{Alpha}_$]
  ^, compiling:(cljs/util.cljc:159:33)
        at clojure.lang.Compiler.load(Compiler.java:7244)
        at clojure.lang.RT.loadResourceScript(RT.java:371)
        at clojure.lang.RT.loadResourceScript(RT.java:362)
        at clojure.lang.RT.load(RT.java:446)
        at clojure.lang.RT.load(RT.java:412)
        at clojure.core$load$fn__5446.invoke(core.clj:5862)
        at clojure.core$load.doInvoke(core.clj:5861)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invoke(core.clj:5667)
        at clojure.core$load_lib$fn__5395.invoke(core.clj:5707)
        at clojure.core$load_lib.doInvoke(core.clj:5706)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invoke(core.clj:630)
        at clojure.core$load_libs.doInvoke(core.clj:5745)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invoke(core.clj:630)
        at clojure.core$require.doInvoke(core.clj:5828)
        at clojure.lang.RestFn.invoke(RestFn.java:2088)
        at cljs.repl$eval71$loading__5338__auto____72.invoke(repl.cljc:9)
        at cljs.repl$eval71.invoke(repl.cljc:9)
        at clojure.lang.Compiler.eval(Compiler.java:6792)
        at clojure.lang.Compiler.eval(Compiler.java:6781)
        at clojure.lang.Compiler.load(Compiler.java:7237)
        at clojure.lang.RT.loadResourceScript(RT.java:371)
        at clojure.lang.RT.loadResourceScript(RT.java:362)
        at clojure.lang.RT.load(RT.java:446)
        at clojure.lang.RT.load(RT.java:412)
        at clojure.core$load$fn__5446.invoke(core.clj:5862)
        at clojure.core$load.doInvoke(core.clj:5861)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invoke(core.clj:5667)
        at clojure.core$load_lib$fn__5395.invoke(core.clj:5707)
        at clojure.core$load_lib.doInvoke(core.clj:5706)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invoke(core.clj:630)
        at clojure.core$load_libs.doInvoke(core.clj:5745)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invoke(core.clj:630)
        at clojure.core$require.doInvoke(core.clj:5828)
        at clojure.lang.RestFn.invoke(RestFn.java:3659)
        at figwheel_sidecar.repl$eval65$loading__5338__auto____66.invoke(repl.clj:1)
        at figwheel_sidecar.repl$eval65.invoke(repl.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6792)
        at clojure.lang.Compiler.eval(Compiler.java:6781)
        at clojure.lang.Compiler.load(Compiler.java:7237)
        at clojure.lang.RT.loadResourceScript(RT.java:371)
        at clojure.lang.RT.loadResourceScript(RT.java:362)
        at clojure.lang.RT.load(RT.java:446)
        at clojure.lang.RT.load(RT.java:412)
        at clojure.core$load$fn__5446.invoke(core.clj:5862)
        at clojure.core$load.doInvoke(core.clj:5861)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invoke(core.clj:5667)
        at clojure.core$load_lib$fn__5395.invoke(core.clj:5707)
        at clojure.core$load_lib.doInvoke(core.clj:5706)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invoke(core.clj:630)
        at clojure.core$load_libs.doInvoke(core.clj:5745)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invoke(core.clj:630)
        at clojure.core$require.doInvoke(core.clj:5828)
        at clojure.lang.RestFn.invoke(RestFn.java:436)
        at user$eval5.invoke(form-init3810615810298081704.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6792)
        at clojure.lang.Compiler.eval(Compiler.java:6781)
        at clojure.lang.Compiler.load(Compiler.java:7237)
        at clojure.lang.Compiler.loadFile(Compiler.java:7175)
        at clojure.main$load_script.invoke(main.clj:275)
        at clojure.main$init_opt.invoke(main.clj:280)
        at clojure.main$initialize.invoke(main.clj:308)
        at clojure.main$null_opt.invoke(main.clj:343)
        at clojure.main$main.doInvoke(main.clj:421)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at clojure.lang.Var.invoke(Var.java:383)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.Var.applyTo(Var.java:700)
        at clojure.main.main(main.java:37)
Caused by: java.util.regex.PatternSyntaxException: Unknown inline modifier near index 2
(?U)^[\p{Alpha}_$]
  ^
        at java.util.regex.Pattern.error(Pattern.java:1713)
        at java.util.regex.Pattern.group0(Pattern.java:2519)
        at java.util.regex.Pattern.sequence(Pattern.java:1806)
        at java.util.regex.Pattern.expr(Pattern.java:1752)
        at java.util.regex.Pattern.compile(Pattern.java:1460)
        at java.util.regex.Pattern.<init>(Pattern.java:1133)
        at java.util.regex.Pattern.compile(Pattern.java:823)
        at clojure.lang.LispReader$RegexReader.invoke(LispReader.java:505)
        at clojure.lang.LispReader$DispatchReader.invoke(LispReader.java:682)
        at clojure.lang.LispReader.read(LispReader.java:255)
        at clojure.lang.LispReader.readDelimitedList(LispReader.java:1189)
        at clojure.lang.LispReader$ListReader.invoke(LispReader.java:1038)
        at clojure.lang.LispReader.read(LispReader.java:255)
        at clojure.lang.LispReader.readDelimitedList(LispReader.java:1189)
        at clojure.lang.LispReader$ListReader.invoke(LispReader.java:1038)
        at clojure.lang.LispReader.read(LispReader.java:255)
        at clojure.lang.LispReader.read(LispReader.java:195)
        at clojure.lang.Compiler.load(Compiler.java:7232)
        ... 76 more
Subprocess failed

those errors I am getting

**Comment by ivanbokii** [comment]
@bhauman kind of the same one, the only difference is the line number. In my case it's `cljs/util.clj:158:33`

```
Exception in thread "main" java.util.regex.PatternSyntaxException: Unknown inline modifier near index 2
(?U)^[\p{Alpha}_$]
  ^, compiling:(cljs/util.clj:158:33)
	at clojure.lang.Compiler.load(Compiler.java:7137)
	at clojure.lang.RT.loadResourceScript(RT.java:370)
	at clojure.lang.RT.loadResourceScript(RT.java:361)
	at clojure.lang.RT.load(RT.java:440)
	at clojure.lang.RT.load(RT.java:411)
	at clojure.core$load$fn__5066.invoke(core.clj:5641)
	at clojure.core$load.doInvoke(core.clj:5640)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5446)
	at clojure.core$load_lib$fn__5015.invoke(core.clj:5486)
	at clojure.core$load_lib.doInvoke(core.clj:5485)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:626)
	at clojure.core$load_libs.doInvoke(core.clj:5524)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:626)
	at clojure.core$require.doInvoke(core.clj:5607)
	at clojure.lang.RestFn.invoke(RestFn.java:2088)
	at cljs.repl$eval71$loading__4958__auto____72.invoke(repl.clj:9)
	at cljs.repl$eval71.invoke(repl.clj:9)
	at clojure.lang.Compiler.eval(Compiler.java:6703)
	at clojure.lang.Compiler.eval(Compiler.java:6692)
	at clojure.lang.Compiler.load(Compiler.java:7130)
	at clojure.lang.RT.loadResourceScript(RT.java:370)
	at clojure.lang.RT.loadResourceScript(RT.java:361)
	at clojure.lang.RT.load(RT.java:440)
	at clojure.lang.RT.load(RT.java:411)
	at clojure.core$load$fn__5066.invoke(core.clj:5641)
	at clojure.core$load.doInvoke(core.clj:5640)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5446)
	at clojure.core$load_lib$fn__5015.invoke(core.clj:5486)
	at clojure.core$load_lib.doInvoke(core.clj:5485)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:626)
	at clojure.core$load_libs.doInvoke(core.clj:5524)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:626)
	at clojure.core$require.doInvoke(core.clj:5607)
	at clojure.lang.RestFn.invoke(RestFn.java:3659)
	at figwheel_sidecar.repl$eval65$loading__4958__auto____66.invoke(repl.clj:1)
	at figwheel_sidecar.repl$eval65.invoke(repl.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6703)
	at clojure.lang.Compiler.eval(Compiler.java:6692)
	at clojure.lang.Compiler.load(Compiler.java:7130)
	at clojure.lang.RT.loadResourceScript(RT.java:370)
	at clojure.lang.RT.loadResourceScript(RT.java:361)
	at clojure.lang.RT.load(RT.java:440)
	at clojure.lang.RT.load(RT.java:411)
	at clojure.core$load$fn__5066.invoke(core.clj:5641)
	at clojure.core$load.doInvoke(core.clj:5640)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5446)
	at clojure.core$load_lib$fn__5015.invoke(core.clj:5486)
	at clojure.core$load_lib.doInvoke(core.clj:5485)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:626)
	at clojure.core$load_libs.doInvoke(core.clj:5524)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:626)
	at clojure.core$require.doInvoke(core.clj:5607)
	at clojure.lang.RestFn.invoke(RestFn.java:436)
	at user$eval5.invoke(form-init642727941869797972.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6703)
	at clojure.lang.Compiler.eval(Compiler.java:6692)
	at clojure.lang.Compiler.load(Compiler.java:7130)
	at clojure.lang.Compiler.loadFile(Compiler.java:7086)
	at clojure.main$load_script.invoke(main.clj:274)
	at clojure.main$init_opt.invoke(main.clj:279)
	at clojure.main$initialize.invoke(main.clj:307)
	at clojure.main$null_opt.invoke(main.clj:342)
	at clojure.main$main.doInvoke(main.clj:420)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.util.regex.PatternSyntaxException: Unknown inline modifier near index 2
(?U)^[\p{Alpha}_$]
  ^
	at java.util.regex.Pattern.error(Pattern.java:1713)
	at java.util.regex.Pattern.group0(Pattern.java:2519)
	at java.util.regex.Pattern.sequence(Pattern.java:1806)
	at java.util.regex.Pattern.expr(Pattern.java:1752)
	at java.util.regex.Pattern.compile(Pattern.java:1460)
	at java.util.regex.Pattern.<init>(Pattern.java:1133)
	at java.util.regex.Pattern.compile(Pattern.java:823)
	at clojure.lang.LispReader$RegexReader.invoke(LispReader.java:439)
	at clojure.lang.LispReader$DispatchReader.invoke(LispReader.java:616)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1138)
	at clojure.lang.LispReader$ListReader.invoke(LispReader.java:972)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1138)
	at clojure.lang.LispReader$ListReader.invoke(LispReader.java:972)
	at clojure.lang.LispReader.read(LispReader.java:183)
	at clojure.lang.Compiler.load(Compiler.java:7126)
	... 76 more
Subprocess failed
```

**Comment by bhauman** [comment]
Are you both using Java8?

**Comment by ivanbokii** [comment]
No, just Java 6

**Comment by bhauman** [comment]
You will need to update to Java 8.

**Comment by bantyg** [comment]
I am also using java 6

**Comment by bantyg** [comment]
The problem was java version. I have updated to 8 now .Its working fine now.
Thanx.

**Comment by boxed** [comment]
Might I suggest adding a java version check and a nicer error message? This was biting me too and it wasn't super easy to find this thread in a google search.

**Comment by bhauman** [comment]
Yeah this is a requirement for the using ClojureScript now.

Maybe contribute the requirement to the om tutotial?  This is where folks
are having a hard time.

**Comment by boxed** [comment]
Om tutorial isn't much good. I wasn't using Om for example. This is a problem with leiningen.
