### ISSUE TITLE
Running in node.js needs documentation

### ISSUE THREAD

**Issue by chr15m** [bhauman/lein-figwheel#187]
"You can use figwheel to live code ClojureScript in Node.js!" This fills me with excitement. Is it possible to document a small quick-start for setting up the figwheel-on-node.js workflow? Hopefully I'm not missing something obvious!

**Comment by honzabrecka** [comment]
It's easy: Let's say you have a cljsbuild build called "server". To your main file (it's that one where you set the *main-cli-fn* function) add: `(:requirements [figwheel.client :as fw])` and at the end of that file put `(fw/start {:build-id "server"})`. Now if you compile your code and run it, it should complain that ws (a node lib) hasn't been installed. Install it with `npm install ws`. Now your're ready to run `lein figwheel server`. Wait until it says it's ready and then run your compiled application. You should see REPL prompt.

Note: It currently works only on mac.

**Comment by bhauman** [comment]
It would be great if someone wanted to contribute instructions to the Wiki.

There is also this helpful snippit on how to use express with figwheel

https://gist.github.com/bhauman/c63123a5c655d77c3e7f

**Comment by chr15m** [comment]
I am sure I am doing something stupid here, but when I clone lein-figwheel and then `cd example && lein figwheel` I get the following error:

```
$ lein figwheel
Figwheel: Starting server at http://localhost:3449
Focusing on build ids: example
Compiling "resources/public/js/example.js" from ["src" "../support/src"]...
WARNING: record? already refers to: cljs.core/record? being replaced by: ankha.core/record? at line 29 file:/home/chrism/.m2/repository/ankha/ankha/0.1.4/ankha-0.1.4.jar!/ankha/core.cljs
Compiling "resources/public/js/example.js" failed.
clojure.lang.ExceptionInfo: failed compiling file:target/figwheel_temp/example/figwheel/connect.cljs
 at clojure.core$ex_info.invoke (core.clj:4593)
Caused by: clojure.lang.ExceptionInfo: Nested #()s are not allowed at line 1 /home/chrism/dev/lein-figwheel/support/src/figwheel/client.cljs
 at clojure.core$ex_info.invoke (core.clj:4593)
Caused by: clojure.lang.ExceptionInfo: Nested #()s are not allowed
 at clojure.core$ex_info.invoke (core.clj:4593)
Caused by: java.lang.IllegalStateException: Nested #()s are not allowed
 at clojure.tools.reader$read_fn.invoke (reader.clj:515)

WARNING: Use of undeclared Var figwheel.client.file-reloading/reload-js-files at line 90 ../support/src/figwheel/client.cljs
WARNING: Use of undeclared Var figwheel.client.file-reloading/reload-css-files at line 153 ../support/src/figwheel/client.cljs
```

The figwheel server is actually launched but when I access `localhost:3449` I get a 404 on `js/examplej.s`.

`Leiningen 2.5.1 on Java 1.7.0_75 OpenJDK 64-Bit Server VM`

**Comment by bhauman** [comment]
you are in lining an on load handler in your config. It needs to be a reference to an function in your file.  

Could you send your build config so I can see it?

**Comment by chr15m** [comment]
It's not my project it's the example folder inside lein-figwheel itself.

**Comment by bhauman** [comment]
Yes the connect.cljs script gets generated from your project. And it has a
syntax error in it becase somehow a nested form like #(  #(  ) ) is getting
created.

**Comment by jakubholynet** [comment]
See https://github.com/bhauman/lein-figwheel/wiki/Node.js-development-with-figwheel

**Comment by bhauman** [comment]
Thanks for this!

Just wanted to let you know that the  :main build option works for node so that you don't have to create the connect script. Your :output-to should be the connect script.

You may want to try that

**Comment by jakubholynet** [comment]
Thanks! I did not know that. I have updated the page accordingly.

**Comment by jakubholynet** [comment]
@bhauman I'd really appreciate if you could check also the newly added [Node.js module development with figwheel](https://github.com/bhauman/lein-figwheel/wiki/Node.js-development-with-figwheel#nodejs-module-development-with-figwheel). Thank you!

**Comment by bhauman** [comment]
This looks great! I think the first line of the first section needs an adjustment? No node init script is required now. Right?

**Comment by jakubholynet** [comment]
@bhauman Not sure what you mean by "the first line of the first section". I believe I removed all references to an init script. Or haven't I? Feel free to edit the page if you find something to correct!

**Comment by frankhale** [comment]
I've been trying to get figwheel to play nice with Express. I am having trouble getting the configuration correct. @bhauman do you mind posting a small example project that incorporates your Express sample code here: https://gist.github.com/bhauman/c63123a5c655d77c3e7f

I've followed along on this thread and the resulting wiki and gists but am having issues running my app with lein figwheel. Once I start my node app everything looks like it's working but figwheel will be unable to find various resources in the target folder.

If need be I can post my sample project, I'm sure I am not doing something right or there are implied tasks that I don't know yet.

**Comment by frankhale** [comment]
@honzabrecka, just noticed where you said this only works on Mac. Is that true? I'm on Windows and this will be a huge bummer if this is true.

I start up lein figwheel, no problem, works wonderfully. Then I start my app. It connects to figwheel, figwheel opens up REPL and then my running app spits out messages saying:

NOTE: While figwheel seems to be running it cannot load any changed files. It will complain about more files it can't find in the target folder.

```
C:\Users\FrankDev\Desktop\hello>node target\server-dev\hello-express.js
Express server listening on port 3000
Figwheel: trying to open cljs reload socket
Figwheel: socket connection established
Figwheel: Error loading file /cljs/pprint.js
Error: Cannot find module '/cljs/pprint.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at C:\Users\FrankDev\Desktop\hello\target\server-dev\figwheel\client\file_reloading.js:605:51
    at C:\Users\FrankDev\Desktop\hello\target\server-dev\figwheel\client\file_reloading.js:617:4
    at figwheel$client$file_reloading$reload_file (C:\Users\FrankDev\Desktop\hello\target\server-dev\figwheel\client\file_reloading.js:656:57)

    at figwheel$client$file_reloading$blocking_load (C:\Users\FrankDev\Desktop\hello\target\server-dev\figwheel\client\file_reloading.js:684:4
4)
    at C:\Users\FrankDev\Desktop\hello\target\server-dev\figwheel\client\file_reloading.js:792:63
    at C:\Users\FrankDev\Desktop\hello\target\server-dev\figwheel\client\file_reloading.js:861:51
Figwheel: Error loading file ../cljs/pprint.js
```

**Comment by bhauman** [comment]
@frankhale I don't have a windows machine. There is obviously some issue with the loading path. 

It's obviously loading the initial files.  But it seems that it's having a hard time with the subsequent files. 

You should really be using an output directory that isn't the root.

**Comment by bhauman** [comment]
Can you post your current project to github?

**Comment by frankhale** [comment]
I will post it. Thanks!

**Comment by frankhale** [comment]
Here is the code:

https://github.com/frankhale/express-hello-world-clojurescript/tree/figwheel

**Comment by bhauman** [comment]
Try making the :output-dir "target/server-dev/out" and get rid of the ecmascript5 stuff.

**Comment by bhauman** [comment]
Oh!!! and you have to set the :asset-path!!!

**Comment by bhauman** [comment]
whenever you use :main you have to have an :asset-path

**Comment by frankhale** [comment]
Thanks @bhauman for the feedback. I've tried your suggestions but I'm still seeing the same problems. I'll try it on another machine when I get home and see if it has issues there. Thanks!

**Comment by frankhale** [comment]
Okay, this appears to be a Windows issue. My project with figwheel works fine on Linux.

**Comment by bhauman** [comment]
This is an opportunity for us to fix this if you are interested. I'm not available tomorrow but I will be on Saturday.

**Comment by frankhale** [comment]
Definitely, I have a vested interest in this working on Windows as I am on Windows 90% of the time. I'll dig a little deeper tomorrow and see if I can find anything out. Thanks @bhauman!!! By the way, totally awesome talk at StrangeLoop 2015!!! Thank you for Dev Cards, I hope to play with this soon!

**Comment by jakubholynet** [comment]
Could it be a problem with `/` in the paths? Just a wild guess...

Regarding
> whenever you use :main you have to have an :asset-path

It would be nice if Figwheel warned if :main is used w/o asset-path :)

**Comment by bhauman** [comment]
@frankhale figwheel.client.file-reloading/reload-file* function is where the problem is.

**Comment by bhauman** [comment]
@frankhale glad you liked the talk, thanks!
@jacubholynet unfortunately it's not the "/"

**Comment by frankhale** [comment]
I'm going to look at this now, thanks for pointing me to the function to look at!

**Comment by frankhale** [comment]
In the reload-file* function root is empty on Windows because it splits on "/" which the Windows path doesn't contain.

Just to test I changed it to "\\" which seems to resolve the issue. It'd be nice if there was a way to get the platform path separator somehow. 

```clojure
root (string/join "\\" (reverse (drop 2 (reverse (string/split js/__dirname "\\")))))
```

**Comment by bhauman** [comment]
I really thought that the node js `require`  worked for url paths that contain "/" on windows.

**Comment by bhauman** [comment]
@frankhale I think that root is supposed to be blank?  I'm really flying in the dark on this one.

Can you send me a small section of your cljs_deps.js file? Like 3 lines is enough. It should be in your output-dir.  

It will show me the paths that are being used on your system.

**Comment by frankhale** [comment]
Here is my cljs_deps.js

```
goog.addDependency("base.js", ['goog'], []);
goog.addDependency("../cljs/core.js", ['cljs.core'], ['goog.string', 'goog.object', 'goog.string.StringBuffer', 'goog.array']);
goog.addDependency("../hello_express_clojurescript/util.js", ['hello_express_clojurescript.util'], ['cljs.core']);
goog.addDependency("../clojure/string.js", ['clojure.string'], ['goog.string', 'cljs.core', 'goog.string.StringBuffer']);
goog.addDependency("../hiccups/runtime.js", ['hiccups.runtime'], ['cljs.core', 'clojure.string']);
goog.addDependency("../5F07AA1.js", ['cljs.nodejs'], ['cljs.core']);
goog.addDependency("../hello_express_clojurescript/views.js", ['hello_express_clojurescript.views'], ['hiccups.runtime', 'cljs.core', 'cljs.nodejs']);
goog.addDependency("../cljs/core/async/impl/protocols.js", ['cljs.core.async.impl.protocols'], ['cljs.core']);
goog.addDependency("../cljs/core/async/impl/ioc_helpers.js", ['cljs.core.async.impl.ioc_helpers'], ['cljs.core', 'cljs.core.async.impl.protocols']);
goog.addDependency("../cljs/core/async/impl/buffers.js", ['cljs.core.async.impl.buffers'], ['cljs.core', 'cljs.core.async.impl.protocols']);
goog.addDependency("../cljs/core/async/impl/dispatch.js", ['cljs.core.async.impl.dispatch'], ['cljs.core', 'cljs.core.async.impl.buffers', 'goog.async.nextTick']);
goog.addDependency("../cljs/core/async/impl/channels.js", ['cljs.core.async.impl.channels'], ['cljs.core.async.impl.dispatch', 'cljs.core', 'cljs.core.async.impl.buffers', 'cljs.core.async.impl.protocols']);
goog.addDependency("../figwheel/client/utils.js", ['figwheel.client.utils'], ['cljs.core', 'clojure.string']);
goog.addDependency("../cljs/reader.js", ['cljs.reader'], ['goog.string', 'cljs.core', 'goog.string.StringBuffer']);
goog.addDependency("../figwheel/client/socket.js", ['figwheel.client.socket'], ['cljs.core', 'figwheel.client.utils', 'cljs.reader']);
goog.addDependency("../cljs/core/async/impl/timers.js", ['cljs.core.async.impl.timers'], ['cljs.core.async.impl.channels', 'cljs.core.async.impl.dispatch', 'cljs.core', 'cljs.core.async.impl.protocols']);
goog.addDependency("../cljs/core/async.js", ['cljs.core.async'], ['cljs.core.async.impl.channels', 'cljs.core.async.impl.dispatch', 'cljs.core', 'cljs.core.async.impl.buffers', 'cljs.core.async.impl.protocols', 'cljs.core.async.impl.ioc_helpers', 'cljs.core.async.impl.timers']);
goog.addDependency("../clojure/set.js", ['clojure.set'], ['cljs.core']);
goog.addDependency("../figwheel/client/file_reloading.js", ['figwheel.client.file_reloading'], ['goog.string', 'goog.net.jsloader', 'goog.Uri', 'cljs.core', 'goog.object', 'cljs.core.async', 'clojure.set', 'figwheel.client.utils', 'clojure.string']);
goog.addDependency("../figwheel/client/heads_up.js", ['figwheel.client.heads_up'], ['goog.string', 'cljs.core', 'cljs.core.async', 'figwheel.client.socket', 'clojure.string']);
goog.addDependency("../hello_express_clojurescript/routes.js", ['hello_express_clojurescript.routes'], ['cljs.core', 'hello_express_clojurescript.util', 'cljs.nodejs', 'hello_express_clojurescript.views']);
goog.addDependency("../cljs/repl.js", ['cljs.repl'], ['cljs.core']);
goog.addDependency("../figwheel/client.js", ['figwheel.client'], ['goog.userAgent.product', 'goog.Uri', 'cljs.core', 'cljs.core.async', 'figwheel.client.file_reloading', 'figwheel.client.utils', 'cljs.repl', 'figwheel.client.heads_up', 'figwheel.client.socket', 'clojure.string']);
goog.addDependency("../hello_express_clojurescript/core.js", ['hello_express_clojurescript.core'], ['cljs.core', 'cljs.nodejs', 'hello_express_clojurescript.views', 'hello_express_clojurescript.routes', 'figwheel.client']);
goog.addDependency("../figwheel/connect.js", ['figwheel.connect'], ['cljs.core', 'hello_express_clojurescript.core', 'figwheel.client', 'figwheel.client.utils']);
goog.addDependency("../1BA16AC.js", ['cljs.nodejscli'], ['cljs.core', 'cljs.nodejs']);
```

**Comment by frankhale** [comment]
I don't have a proper fix for this, this is just a quick hack that seems to work. I only changed root and path.

Here is the complete reload-file* function from file_reloading.cljs. 

```clojure
(def reload-file*
  (condp = (utils/host-env?)
    :node
    (fn [request-url callback]
      (dev-assert (string? request-url) (not (nil? callback)))
      (let [root (string/join "\\" (reverse (drop 2 (reverse (string/split js/__dirname "\\")))))
            path (str root "\\" (fix-node-request-url request-url))]
        (aset (.-cache js/require) path nil)
        (callback (try
                    (js/require path)
                    (catch js/Error e
                      (utils/log :error (str  "Figwheel: Error loading file " path))
                      (utils/log :error (.-stack e))
                      false)))))
    :html (fn [request-url callback]
            (dev-assert (string? request-url) (not (nil? callback)))
            (let [deferred (loader/load (add-cache-buster request-url)
                                        #js { :cleanupWhenDone true })]
              (.addCallback deferred #(apply callback [true]))
              (.addErrback deferred #(apply callback [false]))))
    (fn [a b] (throw "Reload not defined for this platform"))))
```

**Comment by frankhale** [comment]
I think it only works because it's getting a full path for the require instead of a relative one. You said root should possibly be empty so my assumption that it was wrong when root was empty is probably not correct. I'll play some more with this now.

**Comment by frankhale** [comment]
I keep wanting to fix root. When I set root it works on Windows. The js/__dirname is pointing to the folder file_reloading.cljs is in and so I assume require is trying to require from there when root is empty and failing because what it needs is not in that folder.

**Comment by frankhale** [comment]
What about this? Of course me knowing absolutely nothing about how figwheel works internally I could be way off base.

If the root gathering code returns empty use the Windows path separator otherwise just use / as before.

```clojure
(defn get-path-sep []
  (if (> (reverse (drop 2 (reverse (string/split js/__dirname "/")))) 0) "/" "\\"))

; ......

let [path-sep (get-path-sep)
      root (string/join path-sep (reverse (drop 2 (reverse (string/split js/__dirname path-sep)))))
      path (str root path-sep (fix-node-request-url request-url))]
```
