### ISSUE TITLE
Javascript error crashes figwheel repl

### ISSUE THREAD

**Issue by grav** [bhauman/lein-figwheel#233]
If I start a clean figwheel project and provoke a javascript error, the figwheel repl crashes:

```
$ lein new figwheel fig-test 
$ cd fig-test && lein figwheel
[open browser at localhost:3449]
cljs.user=> (foo/bar)
WARNING: No such namespace: foo, could not locate foo.cljs, foo.cljc, or Closure namespace "" at line 1 <cljs repl>
WARNING: Use of undeclared Var foo/bar at line 1 <cljs repl>
#object[ReferenceError ReferenceError: Can't find variable: foo]
java.lang.IllegalArgumentException: Not a file: http://localhost:3449/js/compiled/out/figwheel/client/utils.js
	at clojure.java.io$fn__9085.invoke(io.clj:63)
	at clojure.java.io$fn__9059$G__9041__9064.invoke(io.clj:35)
	at clojure.java.io$file.invoke(io.clj:414)
	at cljs.repl$mapped_frame.invoke(repl.cljc:279)
...
	at clojure.main$null_opt.invoke(main.clj:343)
	at clojure.main$main.doInvoke(main.clj:421)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Subprocess failed
```

The template has cljs 1.7.122 as dependency. Downgrading to 1.7.48 seems to help.

**Comment by bhauman** [comment]
Thanks for the report. I'll check it out.

**Comment by bhauman** [comment]
I'm working hard on this.  Almost finished.
