### ISSUE TITLE
Running snapshot, NPE on current master?

### ISSUE THREAD

**Issue by Quantisan** [bhauman/lein-figwheel#271]
I'm trying to add a feature. However, I pulled the latest master and tried to run `0.5.0-SNAPSHOT` as is, that failed with a NPE. Is the current `master` stable?

I `lein install`: `figwheel`, `sidecar`, and then `plugin`. Then I should be able to use `0.5.0-SNAPSHOT` locally right?

Here's the NPE trace:

```
$ lein figwheel
Figwheel: Starting server at http://localhost:3449
Figwheel: Watching build - dev
Compiling "resources/public/js/compiled/app.js" from ["src/cljs" "env/dev/cljs"]...
Successfully compiled "resources/public/js/compiled/app.js" in 4.363 seconds.
java.lang.NullPointerException
	at clojure.core$deref_future.invoke(core.clj:2186)
	at clojure.core$deref.invoke(core.clj:2207)
	at figwheel_sidecar.system$figwheel_cljs_repl_STAR_.invoke(system.clj:496)
	at figwheel_sidecar.system$build_switching_cljs_repl_STAR_.invoke(system.clj:501)
	at figwheel_sidecar.system$build_switching_cljs_repl.invoke(system.clj:519)
	at figwheel_sidecar.system$build_switching_cljs_repl.invoke(system.clj:517)
	at figwheel_sidecar.system$start_figwheel_and_cljs_repl_BANG_.invoke(system.clj:531)
	at figwheel_sidecar.system$run_autobuilder.invoke(system.clj:545)
	at user$eval16360.invoke(form-init919860803433538560.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6782)
	at clojure.lang.Compiler.eval(Compiler.java:6772)
	at clojure.lang.Compiler.load(Compiler.java:7227)
	at clojure.lang.Compiler.loadFile(Compiler.java:7165)
	at clojure.main$load_script.invoke(main.clj:275)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invoke(main.clj:308)
	at clojure.main$null_opt.invoke(main.clj:343)
	at clojure.main$main.doInvoke(main.clj:421)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Subprocess failed
```

**Comment by bhauman** [comment]
This is under active development and this error means that your build doesn't have a compiler env associated with it.

You may want to try a solid `lein clean`. and make sure that you do not have old compiled classes hanging around.

**Comment by bhauman** [comment]
actually I'm getting the same error :)

**Comment by bhauman** [comment]
Found it and pushing fix.

**Comment by Quantisan** [comment]
:+1: thanks for the quick response!
