### ISSUE TITLE
"No such var" with Clojurescript 1.7.170 and figwheel-sidecar

### ISSUE THREAD

**Issue by mtruyens** [bhauman/lein-figwheel#287]
With a fresh project under ClojureScript 1.7.170, I get a nasty error. No such error occurs with ClojureScript 1.7.145

Dependencies:
  :dependencies [[org.clojure/clojure "1.7.0"]
                 [org.clojure/clojurescript "1.7.170"]
                 [org.clojure/core.async "0.2.371"]
                 [sablono "0.3.6"]
                 [figwheel-sidecar "0.5.0"]
                 [org.omcljs/om "0.9.0"]]

  :plugins [[lein-cljsbuild "1.1.1"]]

Error: 

Exception in thread "main" java.lang.RuntimeException: No such var: figwheel-sidecar.repl/get-project-cljs-builds, compiling:(/Users/mtruyens/Desktop/om-tut/script/repl.clj:2:31)
	at clojure.lang.Compiler.analyze(Compiler.java:6543)
	at clojure.lang.Compiler.analyze(Compiler.java:6485)
	at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3737)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6725)
	at clojure.lang.Compiler.analyze(Compiler.java:6524)
	at clojure.lang.Compiler.analyze(Compiler.java:6485)
	at clojure.lang.Compiler$MapExpr.parse(Compiler.java:3050)
	at clojure.lang.Compiler.analyze(Compiler.java:6532)
	at clojure.lang.Compiler.analyze(Compiler.java:6485)
	at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3791)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6725)
	at clojure.lang.Compiler.analyze(Compiler.java:6524)
	at clojure.lang.Compiler.analyze(Compiler.java:6485)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:5861)
	at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5296)
	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3925)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6721)
	at clojure.lang.Compiler.analyze(Compiler.java:6524)
	at clojure.lang.Compiler.eval(Compiler.java:6779)
	at clojure.lang.Compiler.load(Compiler.java:7227)
	at clojure.lang.Compiler.loadFile(Compiler.java:7165)
	at clojure.main$load_script.invoke(main.clj:275)
	at clojure.main$script_opt.invoke(main.clj:337)
	at clojure.main$main.doInvoke(main.clj:421)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.RuntimeException: No such var: figwheel-sidecar.repl/get-project-cljs-builds
	at clojure.lang.Util.runtimeException(Util.java:221)
	at clojure.lang.Compiler.resolveIn(Compiler.java:6993)
	at clojure.lang.Compiler.resolve(Compiler.java:6963)
	at clojure.lang.Compiler.analyzeSymbol(Compiler.java:6924)
	at clojure.lang.Compiler.analyze(Compiler.java:6506)
	... 33 more

**Comment by bhauman** [comment]
You are going to need to probably do a lein clean.

Also `get-project-builds` has moved to `figwheel-sidecar.config/get-project-builds`

**Comment by bhauman** [comment]
Hmmm seems like a bunch of folks are depending on that function.  
I'll bring it back and release again.
And then update the wiki.

**Comment by bhauman** [comment]
Actually, I have edited the wiki:

https://github.com/bhauman/lein-figwheel/wiki/Running-figwheel-in-a-Cursive-Clojure-REPL#create-a-scriptreplclj-file

**Comment by bhauman** [comment]
Alright I have pushed "0.5.0-1" and that should resolve this issue.
