### ISSUE TITLE
Unable to run figwheel

### ISSUE THREAD

**Issue by bannerintheUK** [bhauman/lein-figwheel#292]
Completely new to clojurescript and figwheel.
installed latest ubuntu (working)
Installed leiningen 2.5.3 (working)
Lein new figwheel  om -- --om (creates folders and files)
lein figwheel (from inside om folder)

wayne@Linux-Laptop:~/Dev/om$ lein figwheel
Figwheel: Starting server at http://localhost:3449
Figwheel: Watching build - dev
Compiling "resources/public/js/compiled/om.js" from ["src"]...
{:file #object[java.net.URL 0x7651ef53 "file:/home/wayne/Dev/om/src/om/core.cljs"], :line 1, :column 1, :tag :cljs/analysis-error}
ANALYSIS ERROR:  at line 1 file:/home/wayne/Dev/om/src/om/core.cljs on file file:/home/wayne/Dev/om/src/om/core.cljs, line 1, column 1
clojure.lang.ExceptionInfo: Error in component :figwheel-system in system com.stuartsierra.component.SystemMap calling #'com.stuartsierra.component/start {:reason :com.stuartsierra.component/component-function-threw-exception, :function #'com.stuartsierra.component/start, :system-key :figwheel-system, :component #figwheel_sidecar.system.FigwheelSystem{:system #object[clojure.lang.Atom 0x291b9a42 {:status :ready, :val #<SystemMap>}]}, :system #<SystemMap>}
	at clojure.core$ex_info.invoke(core.clj:4593)
	at com.stuartsierra.component$try_action.invoke(component.cljc:119)
	at com.stuartsierra.component$update_system$fn__14937.invoke(component.cljc:139)
	at clojure.lang.ArraySeq.reduce(ArraySeq.java:109)
	at clojure.core$reduce.invoke(core.clj:6518)
	at com.stuartsierra.component$update_system.doInvoke(component.cljc:135)
	at clojure.lang.RestFn.invoke(RestFn.java:445)
	at com.stuartsierra.component$start_system.invoke(component.cljc:163)
	at com.stuartsierra.component$start_system.invoke(component.cljc:161)
	at com.stuartsierra.component.SystemMap.start(component.cljc:178)
	at figwheel_sidecar.system$start_figwheel_BANG_.invoke(system.clj:576)
	at figwheel_sidecar.repl_api$start_figwheel_from_lein.invoke(repl_api.clj:124)
	at user$eval16627.invoke(form-init1048398722992825815.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6782)
	at clojure.lang.Compiler.eval(Compiler.java:6772)
	at clojure.lang.Compiler.load(Compiler.java:7227)
	at clojure.lang.Compiler.loadFile(Compiler.java:7165)
	at clojure.main$load_script.invoke(main.clj:275)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invoke(main.clj:308)
	at clojure.main$null_opt.invoke(main.clj:343)
	at clojure.main$main.doInvoke(main.clj:421)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: clojure.lang.ExceptionInfo: Error in component autobuild-dev in system com.stuartsierra.component.SystemMap calling #'com.stuartsierra.component/start {:reason :com.stuartsierra.component/component-function-threw-exception, :function #'com.stuartsierra.component/start, :system-key "autobuild-dev", :component #figwheel_sidecar.components.cljs_autobuild.CLJSAutobuild{:build-config {:id "dev", :source-paths ["src"], :figwheel {:on-jsload "om.core/on-js-reload", :build-id "dev"}, :build-options {:main om.core, :asset-path "js/compiled/out", :output-to "resources/public/js/compiled/om.js", :output-dir "resources/public/js/compiled/out", :source-map-timestamp true, :optimizations :none}, :compiler-env #object[clojure.lang.Atom 0xc836c7e {:status :ready, :val #CompilerEnv{}}]}, :figwheel-server #figwheel_sidecar.components.figwheel_server.FigwheelServer{:connection-count #object[clojure.lang.Atom 0x847ca9d {:status :ready, :val {}}], :browser-callbacks #object[clojure.lang.Atom 0x21470daa {:status :ready, :val {}}], :ring-handler nil, :file-change-atom #object[clojure.lang.Atom 0x3fd224f7 {:status :ready, :val ()}], :compile-wait-time 10, :builds {"dev" {:id "dev", :source-paths ["src"], :figwheel {:on-jsload "om.core/on-js-reload", :build-id "dev"}, :build-options {:main om.core, :asset-path "js/compiled/out", :output-to "resources/public/js/compiled/om.js", :output-dir "resources/public/js/compiled/out", :source-map-timestamp true, :optimizations :none}, :compiler-env #object[clojure.lang.Atom 0xc836c7e {:status :ready, :val #CompilerEnv{}}]}, "min" {:id "min", :source-paths ["src"], :build-options {:output-to "resources/public/js/compiled/om.js", :main om.core, :optimizations :advanced, :pretty-print false, :output-dir "resources/public/js/compiled/out"}, :compiler-env #object[clojure.lang.Atom 0x7d78f4dc {:status :ready, :val #CompilerEnv{}}]}}, :server-port 3449, :resolved-ring-handler nil, :server-ip nil, :cljs-build-fn #object[figwheel_sidecar.components.cljs_autobuild$eval16388$figwheel_start_and_end_messages__16391$fn__16393 0x6c179b8 "figwheel_sidecar.components.cljs_autobuild$eval16388$figwheel_start_and_end_messages__16391$fn__16393@6c179b8"], :http-server #object[clojure.lang.AFunction$1 0x3f6a99fd "clojure.lang.AFunction$1@3f6a99fd"], :open-file-command nil, :unique-id "/home/wayne/Dev/om", :log-writer #object[java.io.BufferedWriter 0x6fa3d191 "java.io.BufferedWriter@6fa3d191"], :file-md5-atom #object[clojure.lang.Atom 0x6c13bfd9 {:status :ready, :val {}}], :css-dirs ["resources/public/css"], :http-server-root "public"}}, :system #<SystemMap>}
	at clojure.core$ex_info.invoke(core.clj:4593)
	at com.stuartsierra.component$try_action.invoke(component.cljc:119)
	at com.stuartsierra.component$update_system$fn__14937.invoke(component.cljc:139)
	at clojure.lang.ArraySeq.reduce(ArraySeq.java:114)
	at clojure.core$reduce.invoke(core.clj:6518)
	at com.stuartsierra.component$update_system.doInvoke(component.cljc:135)
	at clojure.lang.RestFn.invoke(RestFn.java:445)
	at com.stuartsierra.component$start_system.invoke(component.cljc:163)
	at com.stuartsierra.component$start_system.invoke(component.cljc:161)
	at com.stuartsierra.component.SystemMap.start(component.cljc:178)
	at com.stuartsierra.component$eval14878$fn__14879$G__14868__14881.invoke(component.cljc:5)
	at com.stuartsierra.component$eval14878$fn__14879$G__14867__14884.invoke(component.cljc:5)
	at clojure.lang.Atom.swap(Atom.java:37)
	at clojure.core$swap_BANG_.invoke(core.clj:2238)
	at figwheel_sidecar.system.FigwheelSystem.start(system.clj:117)
	at com.stuartsierra.component$eval14878$fn__14879$G__14868__14881.invoke(component.cljc:5)
	at com.stuartsierra.component$eval14878$fn__14879$G__14867__14884.invoke(component.cljc:5)
	at clojure.lang.Var.invoke(Var.java:379)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.core$apply.invoke(core.clj:632)
	at com.stuartsierra.component$try_action.invoke(component.cljc:117)
	... 25 more
Caused by: java.io.FileNotFoundException: resources/public/js/compiled/om.js (No such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:146)
	at clojure.java.io$fn__9189.invoke(io.clj:229)
	at clojure.java.io$fn__9102$G__9095__9109.invoke(io.clj:69)
	at clojure.java.io$fn__9201.invoke(io.clj:258)
	at clojure.java.io$fn__9102$G__9095__9109.invoke(io.clj:69)
	at clojure.java.io$fn__9163.invoke(io.clj:165)
	at clojure.java.io$fn__9115$G__9091__9122.invoke(io.clj:69)
	at clojure.java.io$reader.doInvoke(io.clj:102)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invoke(core.clj:632)
	at clojure.core$slurp.doInvoke(core.clj:6653)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at figwheel_sidecar.build_middleware.injection$require_connection_script_js.invoke(injection.clj:128)
	at figwheel_sidecar.build_middleware.injection$append_connection_init_BANG_.invoke(injection.clj:135)
	at figwheel_sidecar.build_middleware.injection$hook$fn__15924.invoke(injection.clj:142)
	at figwheel_sidecar.components.cljs_autobuild$eval16388$figwheel_start_and_end_messages__16391$fn__16393.invoke(cljs_autobuild.clj:45)
	at figwheel_sidecar.components.cljs_autobuild.CLJSAutobuild.start(cljs_autobuild.clj:121)
	at com.stuartsierra.component$eval14878$fn__14879$G__14868__14881.invoke(component.cljc:5)
	at com.stuartsierra.component$eval14878$fn__14879$G__14867__14884.invoke(component.cljc:5)
	at clojure.lang.Var.invoke(Var.java:379)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.core$apply.invoke(core.clj:632)
	at com.stuartsierra.component$try_action.invoke(component.cljc:117)
	... 45 more
Subprocess failed

Absolutely no idea as how to remedy
Any assistance appreciated

**Comment by bhauman** [comment]
Make sure you are using Java 8

**Comment by bannerintheUK** [comment]
Thanks for rapid response..

reinstalled java (was running 1.7)

wayne@Linux-Laptop:~/Dev/om$ lein --version
Leiningen 2.5.3 on Java 1.8.0_66 Java HotSpot(TM) 64-Bit Server VM

wayne@Linux-Laptop:~/Dev$ lein new figwheel om -- --om
Generating fresh 'lein new' figwheel project.

wayne@Linux-Laptop:~/Dev$ cd om

wayne@Linux-Laptop:~/Dev/om$ lein figwheel
Figwheel: Starting server at http://localhost:3449
Figwheel: Watching build - dev
Compiling "resources/public/js/compiled/om.js" from ["src"]...
{:file #object[java.net.URL 0x4d17097b "file:/home/wayne/Dev/om/src/om/core.cljs"], :line 1, :column 1, :tag :cljs/analysis-error}
ANALYSIS ERROR:  at line 1 file:/home/wayne/Dev/om/src/om/core.cljs on file file:/home/wayne/Dev/om/src/om/core.cljs, line 1, column 1
clojure.lang.ExceptionInfo: Error in component :figwheel-system in system com.stuartsierra.component.SystemMap calling #'com.stuartsierra.component/start {:reason :com.stuartsierra.component/component-function-threw-exception, :function #'com.stuartsierra.component/start, :system-key :figwheel-system, :component #figwheel_sidecar.system.FigwheelSystem{:system #object[clojure.lang.Atom 0x167046f2 {:status :ready, :val #<SystemMap>}]}, :system #<SystemMap>}
	at clojure.core$ex_info.invoke(core.clj:4593)
	at com.stuartsierra.component$try_action.invoke(component.cljc:119)
	at com.stuartsierra.component$update_system$fn__14937.invoke(component.cljc:139)
	at clojure.lang.ArraySeq.reduce(ArraySeq.java:109)
	at clojure.core$reduce.invoke(core.clj:6518)
	at com.stuartsierra.component$update_system.doInvoke(component.cljc:135)
	at clojure.lang.RestFn.invoke(RestFn.java:445)
	at com.stuartsierra.component$start_system.invoke(component.cljc:163)
	at com.stuartsierra.component$start_system.invoke(component.cljc:161)
	at com.stuartsierra.component.SystemMap.start(component.cljc:178)
	at figwheel_sidecar.system$start_figwheel_BANG_.invoke(system.clj:576)
	at figwheel_sidecar.repl_api$start_figwheel_from_lein.invoke(repl_api.clj:124)
	at user$eval16627.invoke(form-init1527543654581607973.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6782)
	at clojure.lang.Compiler.eval(Compiler.java:6772)
	at clojure.lang.Compiler.load(Compiler.java:7227)
	at clojure.lang.Compiler.loadFile(Compiler.java:7165)
	at clojure.main$load_script.invoke(main.clj:275)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invoke(main.clj:308)
	at clojure.main$null_opt.invoke(main.clj:343)
	at clojure.main$main.doInvoke(main.clj:421)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: clojure.lang.ExceptionInfo: Error in component autobuild-dev in system com.stuartsierra.component.SystemMap calling #'com.stuartsierra.component/start {:reason :com.stuartsierra.component/component-function-threw-exception, :function #'com.stuartsierra.component/start, :system-key "autobuild-dev", :component #figwheel_sidecar.components.cljs_autobuild.CLJSAutobuild{:build-config {:id "dev", :source-paths ["src"], :figwheel {:on-jsload "om.core/on-js-reload", :build-id "dev"}, :build-options {:main om.core, :asset-path "js/compiled/out", :output-to "resources/public/js/compiled/om.js", :output-dir "resources/public/js/compiled/out", :source-map-timestamp true, :optimizations :none}, :compiler-env #object[clojure.lang.Atom 0x2f506649 {:status :ready, :val #CompilerEnv{}}]}, :figwheel-server #figwheel_sidecar.components.figwheel_server.FigwheelServer{:connection-count #object[clojure.lang.Atom 0x17cb2dfd {:status :ready, :val {}}], :browser-callbacks #object[clojure.lang.Atom 0x318be20 {:status :ready, :val {}}], :ring-handler nil, :file-change-atom #object[clojure.lang.Atom 0x38e09b9f {:status :ready, :val ()}], :compile-wait-time 10, :builds {"dev" {:id "dev", :source-paths ["src"], :figwheel {:on-jsload "om.core/on-js-reload", :build-id "dev"}, :build-options {:main om.core, :asset-path "js/compiled/out", :output-to "resources/public/js/compiled/om.js", :output-dir "resources/public/js/compiled/out", :source-map-timestamp true, :optimizations :none}, :compiler-env #object[clojure.lang.Atom 0x2f506649 {:status :ready, :val #CompilerEnv{}}]}, "min" {:id "min", :source-paths ["src"], :build-options {:output-to "resources/public/js/compiled/om.js", :main om.core, :optimizations :advanced, :pretty-print false, :output-dir "resources/public/js/compiled/out"}, :compiler-env #object[clojure.lang.Atom 0x14aec0e4 {:status :ready, :val #CompilerEnv{}}]}}, :server-port 3449, :resolved-ring-handler nil, :server-ip nil, :cljs-build-fn #object[figwheel_sidecar.components.cljs_autobuild$eval16388$figwheel_start_and_end_messages__16391$fn__16393 0x1cebff9f "figwheel_sidecar.components.cljs_autobuild$eval16388$figwheel_start_and_end_messages__16391$fn__16393@1cebff9f"], :http-server #object[clojure.lang.AFunction$1 0x3d01c301 "clojure.lang.AFunction$1@3d01c301"], :open-file-command nil, :unique-id "/home/wayne/Dev/om", :log-writer #object[java.io.BufferedWriter 0x7ed5d439 "java.io.BufferedWriter@7ed5d439"], :file-md5-atom #object[clojure.lang.Atom 0x35c7c5e {:status :ready, :val {}}], :css-dirs ["resources/public/css"], :http-server-root "public"}}, :system #<SystemMap>}
	at clojure.core$ex_info.invoke(core.clj:4593)
	at com.stuartsierra.component$try_action.invoke(component.cljc:119)
	at com.stuartsierra.component$update_system$fn__14937.invoke(component.cljc:139)
	at clojure.lang.ArraySeq.reduce(ArraySeq.java:114)
	at clojure.core$reduce.invoke(core.clj:6518)
	at com.stuartsierra.component$update_system.doInvoke(component.cljc:135)
	at clojure.lang.RestFn.invoke(RestFn.java:445)
	at com.stuartsierra.component$start_system.invoke(component.cljc:163)
	at com.stuartsierra.component$start_system.invoke(component.cljc:161)
	at com.stuartsierra.component.SystemMap.start(component.cljc:178)
	at com.stuartsierra.component$eval14878$fn__14879$G__14868__14881.invoke(component.cljc:5)
	at com.stuartsierra.component$eval14878$fn__14879$G__14867__14884.invoke(component.cljc:5)
	at clojure.lang.Atom.swap(Atom.java:37)
	at clojure.core$swap_BANG_.invoke(core.clj:2238)
	at figwheel_sidecar.system.FigwheelSystem.start(system.clj:117)
	at com.stuartsierra.component$eval14878$fn__14879$G__14868__14881.invoke(component.cljc:5)
	at com.stuartsierra.component$eval14878$fn__14879$G__14867__14884.invoke(component.cljc:5)
	at clojure.lang.Var.invoke(Var.java:379)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.core$apply.invoke(core.clj:632)
	at com.stuartsierra.component$try_action.invoke(component.cljc:117)
	... 25 more
Caused by: java.io.FileNotFoundException: resources/public/js/compiled/om.js (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at clojure.java.io$fn__9189.invoke(io.clj:229)
	at clojure.java.io$fn__9102$G__9095__9109.invoke(io.clj:69)
	at clojure.java.io$fn__9201.invoke(io.clj:258)
	at clojure.java.io$fn__9102$G__9095__9109.invoke(io.clj:69)
	at clojure.java.io$fn__9163.invoke(io.clj:165)
	at clojure.java.io$fn__9115$G__9091__9122.invoke(io.clj:69)
	at clojure.java.io$reader.doInvoke(io.clj:102)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invoke(core.clj:632)
	at clojure.core$slurp.doInvoke(core.clj:6653)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at figwheel_sidecar.build_middleware.injection$require_connection_script_js.invoke(injection.clj:128)
	at figwheel_sidecar.build_middleware.injection$append_connection_init_BANG_.invoke(injection.clj:135)
	at figwheel_sidecar.build_middleware.injection$hook$fn__15924.invoke(injection.clj:142)
	at figwheel_sidecar.components.cljs_autobuild$eval16388$figwheel_start_and_end_messages__16391$fn__16393.invoke(cljs_autobuild.clj:45)
	at figwheel_sidecar.components.cljs_autobuild.CLJSAutobuild.start(cljs_autobuild.clj:121)
	at com.stuartsierra.component$eval14878$fn__14879$G__14868__14881.invoke(component.cljc:5)
	at com.stuartsierra.component$eval14878$fn__14879$G__14867__14884.invoke(component.cljc:5)
	at clojure.lang.Var.invoke(Var.java:379)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.core$apply.invoke(core.clj:632)
	at com.stuartsierra.component$try_action.invoke(component.cljc:117)
	... 45 more
Subprocess failed

**Comment by bhauman** [comment]
OK you can't name the project "om"

You are creating a library named om that is in turn requiring om.  That can't work.

So try

```
lein new figwheel hello
```

**Comment by bannerintheUK** [comment]
Thanks!!

Works like a charm

Assistance much appreciated
