### ISSUE TITLE
crashing with cemerick/friend

### ISSUE THREAD

**Issue by gambhiro** [bhauman/lein-figwheel#346]
Starting with new app,

```
lein new figwheel myapp
```

When I add `[com.cemerick/friend "0.2.1"]` to `:dependencies` in `project.clj`, the `lein figwheel` command crashes. I can't comprehend it, but I see something related to figwheel-sidecar in the stacktrace:

```
Exception in thread "main" java.lang.RuntimeException: No such var: clojure.core.cache/through, compiling:(clojure/core/memoize.clj:79:3)
	at clojure.lang.Compiler.analyze(Compiler.java:6688)
...
	at figwheel_sidecar.repl$eval2124$loading__5569__auto____2125.invoke(repl.clj:1)
	at figwheel_sidecar.repl$eval2124.invokeStatic(repl.clj:1)
	at figwheel_sidecar.repl$eval2124.invoke(repl.clj:1)
...
```

**Comment by gambhiro** [comment]
It just needed to have `[org.clojure/core.cache "0.6.4"]` declared explicitly in the dependencies, all is well now.
