### ISSUE TITLE
Figwheel 0.5.3-* crashes with error related to fipp dependency

### ISSUE THREAD

**Issue by dqdinh** [bhauman/lein-figwheel#398]
Hi, I'm getting the following error when updating to the lastest version of figwheel from 0.5.0-6. I'm not sure what is going on. Seems to be related to 'fipp' (https://github.com/bhauman/lein-figwheel/blob/master/sidecar/project.clj#L29). Any thoughts?

```
Exception in thread "main" java.io.FileNotFoundException: Could not locate fipp/printer__init.class or fipp/printer.clj on classpath., compiling:(puget/printer.clj:1:1)
	at clojure.lang.Compiler.load(Compiler.java:7391)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.loadResourceScript(RT.java:363)
	at clojure.lang.RT.load(RT.java:453)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5677.invoke(core.clj:5893)
	at clojure.core$load.invokeStatic(core.clj:5892)
	at clojure.core$load.doInvoke(core.clj:5876)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5697)
	at clojure.core$load_one.invoke(core.clj:5692)
	at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
	at clojure.core$load_lib.invokeStatic(core.clj:5736)
	at clojure.core$load_lib.doInvoke(core.clj:5717)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$load_libs.invokeStatic(core.clj:5774)
	at clojure.core$load_libs.doInvoke(core.clj:5758)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$require.invokeStatic(core.clj:5796)
	at clojure.core$require.doInvoke(core.clj:5796)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at whidbey.render$eval21114$loading__5569__auto____21115.invoke(render.clj:1)
	at whidbey.render$eval21114.invokeStatic(render.clj:1)
	at whidbey.render$eval21114.invoke(render.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6916)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.loadResourceScript(RT.java:363)
	at clojure.lang.RT.load(RT.java:453)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5677.invoke(core.clj:5893)
	at clojure.core$load.invokeStatic(core.clj:5892)
	at clojure.core$load.doInvoke(core.clj:5876)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5697)
	at clojure.core$load_one.invoke(core.clj:5692)
	at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
	at clojure.core$load_lib.invokeStatic(core.clj:5736)
	at clojure.core$load_lib.doInvoke(core.clj:5717)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$load_libs.invokeStatic(core.clj:5774)
	at clojure.core$load_libs.doInvoke(core.clj:5758)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$require.invokeStatic(core.clj:5796)
	at clojure.core$require.doInvoke(core.clj:5796)
	at clojure.lang.RestFn.invoke(RestFn.java:457)
	at whidbey.repl$eval21001$loading__5569__auto____21002.invoke(repl.clj:1)
	at whidbey.repl$eval21001.invokeStatic(repl.clj:1)
	at whidbey.repl$eval21001.invoke(repl.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6916)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.loadResourceScript(RT.java:363)
	at clojure.lang.RT.load(RT.java:453)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5677.invoke(core.clj:5893)
	at clojure.core$load.invokeStatic(core.clj:5892)
	at clojure.core$load.doInvoke(core.clj:5876)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5697)
	at clojure.core$load_one.invoke(core.clj:5692)
	at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
	at clojure.core$load_lib.invokeStatic(core.clj:5736)
	at clojure.core$load_lib.doInvoke(core.clj:5717)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$load_libs.invokeStatic(core.clj:5774)
	at clojure.core$load_libs.doInvoke(core.clj:5758)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$require.invokeStatic(core.clj:5796)
	at clojure.core$require.doInvoke(core.clj:5796)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at user$eval20997.invokeStatic(form-init7040276384506881046.clj:1)
	at user$eval20997.invoke(form-init7040276384506881046.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6916)
	at clojure.lang.Compiler.eval(Compiler.java:6917)
	at clojure.lang.Compiler.eval(Compiler.java:6917)
	at clojure.lang.Compiler.eval(Compiler.java:6916)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	at clojure.lang.Compiler.loadFile(Compiler.java:7317)
	at clojure.main$load_script.invokeStatic(main.clj:275)
	at clojure.main$init_opt.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invoke(main.clj:277)
	at clojure.main$initialize.invokeStatic(main.clj:308)
	at clojure.main$null_opt.invokeStatic(main.clj:342)
	at clojure.main$null_opt.invoke(main.clj:339)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.io.FileNotFoundException: Could not locate fipp/printer__init.class or fipp/printer.clj on classpath.
```

These are the dependencies in my current project.clj:

```
 :dependencies [[org.clojure/clojure "1.8.0"]
                 [org.clojure/clojurescript "1.8.51"]
                 [org.clojure/core.async "0.2.374"]
                 [com.cemerick/piggieback "0.2.1"]
                 [com.rpl/specter "0.10.0"]
                 [ring/ring "1.4.0"]
                 [ring/ring-defaults "0.2.0"]
                 [ring/ring-json "0.4.0"]
                 [bk/ring-gzip "0.1.1"]
                 [compojure "1.5.0"]
                 [bidi "2.0.9"]
                 [com.cemerick/url "0.1.1"]
                 [kibu/pushy "0.3.6"]
                 [reagent "0.6.0-alpha2"]
                 [re-frame "0.7.0"]
                 [re-com "0.8.3"]
                 [environ "1.0.3"]
                 [figwheel "0.5.3-2"]
                 [figwheel-sidecar "0.5.3-2"]
                 [prismatic/schema "1.0.5"]
                 [cljs-http "0.1.39"]]

  :plugins [[lein-environ "1.0.2"]
            [lein-ring "0.9.7"]
            [lein-figwheel "0.5.3-2"]
            [lein-cljsbuild "1.1.2"]
            [lein-doo "0.1.7-SNAPSHOT"]]
```

**Comment by dqdinh** [comment]
Actually I traced it down to figwheel 0.5.1. From reading the changelog there was a big change here. I think it has something to do with my clojure.repl / sidecar integration.

```
(ns user
  (:require
   [frontend.handler]
   [ring.middleware.reload :refer [wrap-reload]]
   [figwheel-sidecar.repl-api :as figwheel]))

;; Let Clojure warn you when it needs to reflect on types, or when it does math
;; on unboxed numbers. In both cases you should add type annotations to prevent
;; degraded performance.
(set! *warn-on-reflection* true)
(set! *unchecked-math* :warn-on-boxed)
(def http-handler
  (wrap-reload #'frontend.handler/http-handler))

(defn start!
  "Boot up figwheel server."
  []
  (figwheel/start-figwheel!
   {:figwheel-options {:server-port 3333}
    :build-ids ["dev"]
    :all-builds
    [{:id "dev"
      :source-paths ["src/cljs"]
      :figwheel true
      :compiler {:source-map true
                 :pretty-print true
                 :main "frontend.core"
                 :source-map-timestamp true
                 :optimizations :none
                 :output-dir "resources/public/js/out"
                 :asset-path "js/out"
                 :output-to "resources/public/js/main.js"}}]}))

(defn stop!
  "Stop figwheel server."
  []
  (figwheel/stop-figwheel!))

(defn repl
  "Load figwheel cljs browser repl."
  []
  (figwheel/cljs-repl))
```

This is prob an issue specific to my setup. I'll reopen this is if this does not resolve after reading the docs again and trying to figure out what changed. Thanks!

**Comment by gfrivolt** [comment]
I have the same issue

**Comment by bhauman** [comment]
Make sure you do a lein clean.

**Comment by gfrivolt** [comment]
I did `lein clean`, but it fails with the same error what @dqdinh posted. The last version which starts up normaly for me is `0.5.0-6`.

These are my deps:

```
:dependencies [[org.clojure/clojure "1.7.0"]
                 [org.clojure/clojurescript "1.9.36"]
                 [org.omcljs/om "1.0.0-alpha36"]
                 [bidi "2.0.9"]
                 [devcards "0.2.1-7"]
                 [sablono "0.7.2"]
                 [garden "1.3.2"]
                 [cljsjs/react "15.1.0-0"]
                 [cljsjs/react-dom "15.1.0-0"]
                 [cljsjs/d3 "3.5.16-0"]
                 [cljsjs/victory "0.6.0-0"]
                 [cljsjs/nprogress "0.2.0-1"]
                 [figwheel-sidecar "0.5.0-6" :scope "test"]]
```

**Comment by bhauman** [comment]
If you do

lein deps :tree | grep figwheel
lein deps :tree | grep fipp

All the references to figwheel libraries should match.

If you change the lein-fighweel plugin version you need to change the
figwheel-sidecar version as well.

**Comment by gfrivolt** [comment]
I reviewed `~/.lein/profiles.clj` and I found that I had there some pretty old versions. I cleaned it up and it works now. Although I don't have `lein-figwheel`, something else was conflicting.

Thank you for help.
