### ISSUE TITLE
Catch and suppress Component errors when compiling at startup

### ISSUE THREAD

**Issue by danielcompton** [bhauman/lein-figwheel#400]
I got the error below today when compiling my app. The useful line is: `ERROR: Map literal must contain`. Due to the sheer volume of the stack trace (I've removed SystemMap from the log, but that is quite large too), and the fact that Java prints stack traces 'upside-down', it's not always very easy to find that error message.

It would be helpful I think to suppress the lower level Component errors, and only print the direct cause?

Thinking about this some more, perhaps in this specific instance an error should be thrown when compilation fails and it shouldn't get to SystemMap creation? I'm not familiar enough with Figwheel to say though.

```sh
$ lein figwheel
Figwheel: Validating the configuration found in project.clj

Figwheel: Configuration Valid. Starting Figwheel ...
Figwheel: Starting server at http://localhost:3460
Figwheel: Watching build - dev
Compiling "run/resources/public/compiled_dev/myapp.js" from ["dev-src" "src"]...
{:type :reader-exception, :line 17, :column 18, :file "/Users/me/Developer/my-app/src/cljs/my_app/schema.cljs"}
ERROR: Map literal must contain an even number of forms on file <elided>/schema.cljs, line 17, column 18
clojure.lang.ExceptionInfo: Error in component :figwheel-system in system com.stuartsierra.component.SystemMap calling #'com.stuartsierra.component/start {:reason :com.stuartsierra.component/component-function-threw-exception, :function #'com.stuartsierra.component/start, :system-key :figwheel-system, :component #figwheel_sidecar.system.FigwheelSystem{:system #object[clojure.lang.Atom 0x25e1ddb7 {:status :ready, :val #<SystemMap>}]}, :system #<SystemMap>}
        at clojure.core$ex_info.invokeStatic(core.clj:4617)
        at clojure.core$ex_info.invoke(core.clj:4617)
        at com.stuartsierra.component$try_action.invokeStatic(component.cljc:119)
        at com.stuartsierra.component$try_action.invoke(component.cljc:116)
        at com.stuartsierra.component$update_system$fn__15279.invoke(component.cljc:139)
        at clojure.lang.ArraySeq.reduce(ArraySeq.java:109)
        at clojure.core$reduce.invokeStatic(core.clj:6544)
        at clojure.core$reduce.invoke(core.clj:6527)
        at com.stuartsierra.component$update_system.invokeStatic(component.cljc:135)
        at com.stuartsierra.component$update_system.doInvoke(component.cljc:129)
        at clojure.lang.RestFn.invoke(RestFn.java:445)
        at com.stuartsierra.component$start_system.invokeStatic(component.cljc:163)
        at com.stuartsierra.component$start_system.invoke(component.cljc:155)
        at com.stuartsierra.component$start_system.invokeStatic(component.cljc:161)
        at com.stuartsierra.component$start_system.invoke(component.cljc:155)
        at com.stuartsierra.component.SystemMap.start(component.cljc:178)
        at figwheel_sidecar.system$start_figwheel_BANG_.invokeStatic(system.clj:588)
        at figwheel_sidecar.system$start_figwheel_BANG_.invoke(system.clj:585)
        at figwheel_sidecar.repl_api$start_figwheel_from_lein.invokeStatic(repl_api.clj:137)
        at figwheel_sidecar.repl_api$start_figwheel_from_lein.invoke(repl_api.clj:136)
        at user$eval17000.invokeStatic(form-init4657759006730061034.clj:1)
        at user$eval17000.invoke(form-init4657759006730061034.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6927)
        at clojure.lang.Compiler.eval(Compiler.java:6917)
        at clojure.lang.Compiler.load(Compiler.java:7379)
        at clojure.lang.Compiler.loadFile(Compiler.java:7317)
        at clojure.main$load_script.invokeStatic(main.clj:275)
        at clojure.main$init_opt.invokeStatic(main.clj:277)
        at clojure.main$init_opt.invoke(main.clj:277)
        at clojure.main$initialize.invokeStatic(main.clj:308)
        at clojure.main$null_opt.invokeStatic(main.clj:342)
        at clojure.main$null_opt.invoke(main.clj:339)
        at clojure.main$main.invokeStatic(main.clj:421)
        at clojure.main$main.doInvoke(main.clj:384)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at clojure.lang.Var.invoke(Var.java:383)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.Var.applyTo(Var.java:700)
        at clojure.main.main(main.java:37)
Caused by: clojure.lang.ExceptionInfo: Error in component autobuild-dev in system com.stuartsierra.component.SystemMap calling #'com.stuartsierra.component/start {:reason :com.stuartsierra.component/component-function-threw-exception, :function #'com.stuartsierra.component/start, :system-key "autobuild-dev", :component #figwheel_sidecar.components.cljs_autobuild.CLJSAutobuild{:<config elided, but it is large>}
        at clojure.core$ex_info.invokeStatic(core.clj:4617)
        at clojure.core$ex_info.invoke(core.clj:4617)
        at com.stuartsierra.component$try_action.invokeStatic(component.cljc:119)
        at com.stuartsierra.component$try_action.invoke(component.cljc:116)
        at com.stuartsierra.component$update_system$fn__15279.invoke(component.cljc:139)
        at clojure.lang.ArraySeq.reduce(ArraySeq.java:114)
        at clojure.core$reduce.invokeStatic(core.clj:6544)
        at clojure.core$reduce.invoke(core.clj:6527)
        at com.stuartsierra.component$update_system.invokeStatic(component.cljc:135)
        at com.stuartsierra.component$update_system.doInvoke(component.cljc:129)
        at clojure.lang.RestFn.invoke(RestFn.java:445)
        at com.stuartsierra.component$start_system.invokeStatic(component.cljc:163)
        at com.stuartsierra.component$start_system.invoke(component.cljc:155)
        at com.stuartsierra.component$start_system.invokeStatic(component.cljc:161)
        at com.stuartsierra.component$start_system.invoke(component.cljc:155)
        at com.stuartsierra.component.SystemMap.start(component.cljc:178)
        at com.stuartsierra.component$eval15220$fn__15221$G__15210__15223.invoke(component.cljc:5)
        at com.stuartsierra.component$eval15220$fn__15221$G__15209__15226.invoke(component.cljc:5)
        at clojure.lang.Atom.swap(Atom.java:37)
        at clojure.core$swap_BANG_.invokeStatic(core.clj:2260)
        at clojure.core$swap_BANG_.invoke(core.clj:2253)
        at figwheel_sidecar.system.FigwheelSystem.start(system.clj:119)
        at com.stuartsierra.component$eval15220$fn__15221$G__15210__15223.invoke(component.cljc:5)
        at com.stuartsierra.component$eval15220$fn__15221$G__15209__15226.invoke(component.cljc:5)
        at clojure.lang.Var.invoke(Var.java:379)
        at clojure.lang.AFn.applyToHelper(AFn.java:154)
        at clojure.lang.Var.applyTo(Var.java:700)
        at clojure.core$apply.invokeStatic(core.clj:648)
        at clojure.core$apply.invoke(core.clj:641)
        at com.stuartsierra.component$try_action.invokeStatic(component.cljc:117)
        ... 36 more
Caused by: java.io.FileNotFoundException: run/<elided>/myapp.js (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at clojure.java.io$fn__9520.invokeStatic(io.clj:229)
        at clojure.java.io$fn__9520.invoke(io.clj:229)
        at clojure.java.io$fn__9433$G__9426__9440.invoke(io.clj:69)
        at clojure.java.io$fn__9532.invokeStatic(io.clj:258)
        at clojure.java.io$fn__9532.invoke(io.clj:254)
        at clojure.java.io$fn__9433$G__9426__9440.invoke(io.clj:69)
        at clojure.java.io$fn__9494.invokeStatic(io.clj:165)
        at clojure.java.io$fn__9494.invoke(io.clj:165)
        at clojure.java.io$fn__9446$G__9422__9453.invoke(io.clj:69)
        at clojure.java.io$reader.invokeStatic(io.clj:102)
        at clojure.java.io$reader.doInvoke(io.clj:86)
        at clojure.lang.RestFn.invoke(RestFn.java:410)
        at clojure.lang.AFn.applyToHelper(AFn.java:154)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at clojure.core$apply.invokeStatic(core.clj:648)
        at clojure.core$slurp.invokeStatic(core.clj:6657)
        at clojure.core$slurp.doInvoke(core.clj:6657)
        at clojure.lang.RestFn.invoke(RestFn.java:410)
        at figwheel_sidecar.build_middleware.injection$require_connection_script_js.invokeStatic(injection.clj:128)
        at figwheel_sidecar.build_middleware.injection$require_connection_script_js.invoke(injection.clj:115)
        at figwheel_sidecar.build_middleware.injection$append_connection_init_BANG_.invokeStatic(injection.clj:135)
        at figwheel_sidecar.build_middleware.injection$append_connection_init_BANG_.invoke(injection.clj:133)
        at figwheel_sidecar.build_middleware.injection$hook$fn__16286.invoke(injection.clj:142)
        at figwheel_sidecar.components.cljs_autobuild$eval16752$figwheel_start_and_end_messages__16755$fn__16757.invoke(cljs_autobuild.clj:47)
        at figwheel_sidecar.components.cljs_autobuild.CLJSAutobuild.start(cljs_autobuild.clj:140)
        at com.stuartsierra.component$eval15220$fn__15221$G__15210__15223.invoke(component.cljc:5)
        at com.stuartsierra.component$eval15220$fn__15221$G__15209__15226.invoke(component.cljc:5)
        at clojure.lang.Var.invoke(Var.java:379)
        at clojure.lang.AFn.applyToHelper(AFn.java:154)
        at clojure.lang.Var.applyTo(Var.java:700)
        at clojure.core$apply.invokeStatic(core.clj:648)
        at clojure.core$apply.invoke(core.clj:641)
        at com.stuartsierra.component$try_action.invokeStatic(component.cljc:117)
        ... 63 more
Error encountered performing task 'do' with profile(s): 'base,system,user,provided,dev,dev-run'
Subprocess failed
```

**Comment by bhauman** [comment]
This has been fixed already in the latest version of figwheel.  Could you
give it a try?

**Comment by danielcompton** [comment]
Yep that works, thanks!
