### ISSUE TITLE
0.5.3-2 causes `location` error on node.js

### ISSUE THREAD

**Issue by bhagany** [bhauman/lein-figwheel#401]
here's the error:

```
/www/iclexa/out/dev/cljs/core.cljs:4711
     (assoc m k (f (get m k)))))
                ^
ReferenceError: location is not defined
    at /www/iclexa/out/dev/figwheel/client.js:1552:98
    at /www/iclexa/out/dev/cljs/core.cljs:4711:18
    at Function.cljs.core.update_in.cljs$core$IFn$_invoke$arity$3 (/www/iclexa/out/dev/cljs/core.cljs:4711:17)
    at cljs$core$update_in (/www/iclexa/out/dev/cljs/core.cljs:4702:1)
    at figwheel$client$fill_url_template (/www/iclexa/out/dev/figwheel/client.js:1551:28)
    at Timeout._onTimeout (/www/iclexa/out/dev/figwheel/client.js:1693:56)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
```

I've verified that 0.5.3-1 and below work as expected.  To me, it looks like something is making figwheel think that it's running in a browser instead of on node.

**Comment by bhauman** [comment]
Thanks for the report! I'll check into it.
