### ISSUE TITLE
Figwheel not starting properly

### ISSUE THREAD

**Issue by aivijay** [bhauman/lein-figwheel#417]
I had been trying to get a basic figwheel project to run and getting the following error. Seems the same error was around recently and people have mentioned that its fixed and things are fine. But for some reason am getting this error and driving me nuts.

Running on Leiningen 2.6.1 on Java 1.8.0_45 Java HotSpot(TM) 64-Bit Server VM.

Its just a new project created and run.

~/working/clojure-script/testom$ lein figwheel
Figwheel: Validating the configuration found in project.clj

Figwheel: Configuration Valid. Starting Figwheel ...
Figwheel: Starting server at http://0.0.0.0:3449
Figwheel: Watching build - dev
Compiling "resources/public/js/compiled/testom.js" from ["src"]...
Successfully compiled "resources/public/js/compiled/testom.js" in 1.041 seconds.
Figwheel: Starting CSS Watcher for paths  ["resources/public/css"]
clojure.lang.ExceptionInfo: Error in component :css-watcher in system com.stuartsierra.component.SystemMap calling #'com.stuartsierra.component/start {:reason :com.stuartsierra.component/component-function-threw-exception, :function #'com.stuartsierra.component/start, :system-key :css-watcher, :component #figwheel_sidecar.components.file_system_watcher.FileSystemWatcher{:watcher-name "CSS Watcher", :watch-paths ["resources/public/css"], :notification-handler #object[figwheel_sidecar.components.css_watcher$handle_css_notification 0x4ae8bf28 "figwheel_sidecar.components.css_watcher$handle_css_notification@4ae8bf28"], :figwheel-server #figwheel_sidecar.system.FigwheelSystem{:system #object[clojure.lang.Atom 0x7c4d896a {:status :ready, :val #<SystemMap>}], :system-running true}, :log-writer nil}, :system #<SystemMap>}
	at clojure.core$ex_info.invokeStatic(core.clj:4617)
	at clojure.core$ex_info.invoke(core.clj:4617)
	at com.stuartsierra.component$try_action.invokeStatic(component.cljc:119)
	at com.stuartsierra.component$try_action.invoke(component.cljc:116)
	at com.stuartsierra.component$update_system$fn__16529.invoke(component.cljc:139)
	at clojure.lang.ArraySeq.reduce(ArraySeq.java:114)
	at clojure.core$reduce.invokeStatic(core.clj:6544)
	at clojure.core$reduce.invoke(core.clj:6527)
	at com.stuartsierra.component$update_system.invokeStatic(component.cljc:135)
	at com.stuartsierra.component$update_system.doInvoke(component.cljc:129)
	at clojure.lang.RestFn.invoke(RestFn.java:445)
	at com.stuartsierra.component$start_system.invokeStatic(component.cljc:163)
	at com.stuartsierra.component$start_system.invoke(component.cljc:155)
	at com.stuartsierra.component$start_system.invokeStatic(component.cljc:161)
	at com.stuartsierra.component$start_system.invoke(component.cljc:155)
	at com.stuartsierra.component.SystemMap.start(component.cljc:178)
	at figwheel_sidecar.system$start_figwheel_BANG_.invokeStatic(system.clj:594)
	at figwheel_sidecar.system$start_figwheel_BANG_.invoke(system.clj:590)
	at figwheel_sidecar.repl_api$start_figwheel_from_lein.invokeStatic(repl_api.clj:137)
	at figwheel_sidecar.repl_api$start_figwheel_from_lein.invoke(repl_api.clj:136)
	at user$eval18278.invokeStatic(form-init8807151060973655042.clj:1)
	at user$eval18278.invoke(form-init8807151060973655042.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6917)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	at clojure.lang.Compiler.loadFile(Compiler.java:7317)
	at clojure.main$load_script.invokeStatic(main.clj:275)
	at clojure.main$init_opt.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invoke(main.clj:277)
	at clojure.main$initialize.invokeStatic(main.clj:308)
	at clojure.main$null_opt.invokeStatic(main.clj:342)
	at clojure.main$null_opt.invoke(main.clj:339)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.io.IOException: User limit of inotify instances reached or too many open files
	at sun.nio.fs.LinuxWatchService.<init>(LinuxWatchService.java:64)
	at sun.nio.fs.LinuxFileSystem.newWatchService(LinuxFileSystem.java:47)
	at hawk.watcher$fn__127.invoke(watcher.clj:92)
	at clojure.lang.MultiFn.invoke(MultiFn.java:229)
	at hawk.watcher$fn__134.invoke(watcher.clj:100)
	at clojure.lang.MultiFn.invoke(MultiFn.java:229)
	at hawk.core$watch_BANG_.invokeStatic(core.clj:62)
	at hawk.core$watch_BANG_.doInvoke(core.clj:59)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at figwheel_sidecar.watching$watch_BANG_.invokeStatic(watching.clj:71)
	at figwheel_sidecar.watching$watch_BANG_.invoke(watching.clj:40)
	at figwheel_sidecar.components.file_system_watcher.FileSystemWatcher.start(file_system_watcher.clj:21)
	at com.stuartsierra.component$eval16470$fn__16471$G__16460__16473.invoke(component.cljc:5)
	at com.stuartsierra.component$eval16470$fn__16471$G__16459__16476.invoke(component.cljc:5)
	at clojure.lang.Var.invoke(Var.java:379)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$apply.invoke(core.clj:641)
	at com.stuartsierra.component$try_action.invokeStatic(component.cljc:117)
	... 36 more
Subprocess failed

**Comment by bhauman** [comment]
Wow, you are watching so many files you hit a limit.

Try this option in the top level :figwheel in your project.clj
   :hawk-options {:watcher :polling}

**Comment by aivijay** [comment]
I tried the option you mentioned in my projects and it worked fine without any problems.
These are just newly created figwheel projects. Nothing updated in them.

Then I tried you flappy-bird-demo. I updated the option you mentioned. The same error pops up when I try to run "... too many files open".

Question:
1. Are these "too many files open" arising with ref to the OS level or only within figwheel? Is this related to something where I have too many files open on the machine I am working on?

**Comment by aivijay** [comment]
Finally, it seems things are fine. Most probably my machine or maybe there were too many file open or something.
I tried on a different machine and it just worked fine. 

Thanks for your pointers. Will try out hawk watcher as well on the setup where things were failing.
