### ISSUE TITLE
2.2-SNAPSHOT clasCastEsxception

### ISSUE THREAD

**Issue by theophilusx** [bhauman/lein-figwheel#69]
Using lein new reagent template and then updating dependencies following lein ancient :all0w-snapshots :all. Running lein figwheel throws the following exception -

```
java.lang.ClassCastException: java.lang.String cannot be cast to clojure.lang.IFn
	at user$eval9711.invoke(form-init7083026572644416345.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6703)
	at clojure.lang.Compiler.eval(Compiler.java:6693)
	at clojure.lang.Compiler.load(Compiler.java:7130)
	at clojure.lang.Compiler.loadFile(Compiler.java:7086)
	at clojure.main$load_script.invoke(main.clj:274)
	at clojure.main$init_opt.invoke(main.clj:279)
	at clojure.main$initialize.invoke(main.clj:307)
	at clojure.main$null_opt.invoke(main.clj:342)
	at clojure.main$main.doInvoke(main.clj:420)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Subprocess failed
```

Reverting lein-figwheel to 2.0-snapshot and all appears to work.

**Comment by bhauman** [comment]
Can I see your project.clj?  This error is because there is a list in your
figwheel or cljsbuild config. It needs to be a vector.  I'd like to know
which param it is so that I can correct it.

**Comment by theophilusx** [comment]
Sure. It is basically the lein new reagent template default with a couple of extra libs added and update to the versions etc. Appreciate it if you can see the error and if you have time, would really like to know how you identified the issue from that exception (very much still learning this stuff) 

``` clojure
(defproject mcljs-fig "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}

  :source-paths ["src/clj" "src/cljs"]

  :dependencies [[org.clojure/clojure "1.6.0"]
                 [com.facebook/react "0.12.2.1"]
                 [reagent "0.4.3"]
                 [reagent-forms "0.3.9"]
                 [reagent-utils "0.1.2"]
                 [secretary "1.2.1"]
                 [org.clojure/clojurescript "0.0-2665" :scope "provided"]
                 [com.cemerick/piggieback "0.1.5"]
                 [weasel "0.5.0"]
                 [ring "1.3.2"]
                 [ring/ring-defaults "0.1.3"]
                 [prone "0.8.0"]
                 [compojure "1.3.1"]
                 [selmer "0.7.9"]
                 [environ "1.0.0"]
                 [leiningen "2.5.1"]
                 [figwheel "0.2.2-SNAPSHOT"]
                 [json-html "0.2.8"]
                 [liberator "0.12.2"]
                 [cheshire "5.4.0"]
                 [clojurewerkz/money "1.7.0"]
                 [cljs-ajax "0.3.9"]]

  :plugins [
            [lein-cljsbuild "1.0.4"]
            [lein-environ "1.0.0"]
            [lein-ring "0.9.1"]
            [lein-asset-minifier "0.2.2"]]

  :ring {:handler mcljs-fig.handler/app
         :uberwar-name "mcljs-fig.war"}

  :min-lein-version "2.5.0"

  :uberjar-name "mcljs-fig.jar"

  :clean-targets ^{:protect false} ["resources/public/js"]

  :minify-assets
  {:assets
   {"resources/public/css/site.min.css" "resources/public/css/site.css"}}

  :cljsbuild {:builds {:app {:source-paths ["src/cljs"]
                             :compiler {:output-to "resources/public/js/app.js"
                                        :output-dir "resources/public/js/out"
                                        :externs ["react/externs/react.js"]
                                        :optimizations :none
                                        :pretty-print  true}}
                       }}

  :profiles {:dev {:repl-options {:init-ns mcljs-fig.handler
                                  :nrepl-middleware
                                  [cemerick.piggieback/wrap-cljs-repl]}

                   :dependencies [[ring-mock "0.1.5"]
                                  [ring/ring-devel "1.3.2"]
                                  [pjstadig/humane-test-output "0.6.0"]]

                   :plugins [[lein-figwheel "0.2.0-SNAPSHOT"]]

                   :injections [(require 'pjstadig.humane-test-output)
                                (pjstadig.humane-test-output/activate!)]

                   :figwheel {:http-server-root "public"
                              :server-port 3449
                              :css-dirs ["resources/public/css"]
                              :ring-handler mcljs-fig.handler/app}

                   :env {:dev? true}

                   :cljsbuild {:builds {:app {:source-paths ["env/dev/cljs"]
                                              :compiler {:source-map true}}}}}

             :uberjar {:hooks [leiningen.cljsbuild minify-assets.plugin/hooks]
                       :env {:production true}
                       :aot :all
                       :omit-source true
                       :cljsbuild {:jar true
                                   :builds {:app
                                            {:source-paths ["env/prod/cljs"]
                                             :compiler
                                             {:optimizations :advanced
                                              :pretty-print false}}}}}

             :production {:ring {:open-browser? false
                                 :stacktraces?  false
                                 :auto-reload?  false}}})
```

**Comment by bhauman** [comment]
Thanks man,

I found it.  I'll have a fix out in a jiffy.

**Comment by theophilusx** [comment]
No, thank you! Finding issues is much easier than fixing them :-)

Just moved to using lein-figwheel today. Previously, used Austin, but like the idea of live js updates while working etc. Great work - thanks a lot!

**Comment by bhauman** [comment]
Give it a try now.  Also make sure you update the figwheel in :dependencies
to "0.2.2-SNAPSHOT"  as well.

**Comment by theophilusx** [comment]
Do I need to try it from the git repo or have you updated the clojars version?

**Comment by bhauman** [comment]
I updated the 2.2-SNAPSHOT  in Clojars.

**Comment by theophilusx** [comment]
Looks to be working now. Thanks.

**Comment by bhauman** [comment]
great!!
