### ISSUE TITLE
Regression with namespace maps with aliases

### ISSUE THREAD

**Issue by mfikes** [bhauman/lein-figwheel#691]
```clojure
(require '[figwheel4node-server.core :as foo])
```

and then

```clojure
#::foo{:a 1}
```

fails with

```
clojure.lang.ExceptionInfo: No namespace: figwheel4node-server.core found {:type :reader-exception, :line 1, :column 7, :file "<NO_SOURCE_FILE>"}
	at clojure.core$ex_info.invokeStatic(core.clj:4739)
	at clojure.core$ex_info.invoke(core.clj:4739)
	at clojure.tools.reader$read_STAR_.invokeStatic(reader.clj:942)
	at clojure.tools.reader$read_STAR_.invoke(reader.clj:906)
	at clojure.tools.reader$read.invokeStatic(reader.clj:977)
	at clojure.tools.reader$read.invoke(reader.clj:950)
	at cljs.repl$repl_read.invokeStatic(repl.cljc:106)
	at cljs.repl$repl_read.invoke(repl.cljc:85)
	at cljs.repl$repl_read.invokeStatic(repl.cljc:97)
	at cljs.repl$repl_read.invoke(repl.cljc:85)
	at rebel_readline.core$create_buffered_repl_reader_fn$fn__26483$fn__26484.invoke(core.clj:183)
	at cljs.repl$repl_STAR_$read_eval_print__6536$fn__6537.invoke(repl.cljc:949)
	at cljs.repl$repl_STAR_$read_eval_print__6536.invoke(repl.cljc:942)
	at cljs.repl$repl_STAR_$fn__6542$fn__6551.invoke(repl.cljc:998)
	at cljs.repl$repl_STAR_$fn__6542.invoke(repl.cljc:997)
	at cljs.compiler$with_core_cljs.invokeStatic(compiler.cljc:1285)
	at cljs.compiler$with_core_cljs.invoke(compiler.cljc:1274)
	at cljs.repl$repl_STAR_.invokeStatic(repl.cljc:960)
	at cljs.repl$repl_STAR_.invoke(repl.cljc:839)
	at rebel_readline.cljs.repl$repl_STAR_.invokeStatic(repl.clj:72)
	at rebel_readline.cljs.repl$repl_STAR_.invoke(repl.clj:61)
	at clojure.lang.Var.invoke(Var.java:385)
	at figwheel_sidecar.repl$eval19824$fn__19825.invoke(repl.clj:218)
	at clojure.lang.MultiFn.invoke(MultiFn.java:233)
	at figwheel_sidecar.repl$repl.invokeStatic(repl.clj:344)
	at figwheel_sidecar.repl$repl.doInvoke(repl.clj:342)
	at clojure.lang.RestFn.invoke(RestFn.java:436)
	at figwheel_sidecar.system$start_figwheel_repl.invokeStatic(system.clj:520)
	at figwheel_sidecar.system$start_figwheel_repl.invoke(system.clj:511)
	at figwheel_sidecar.system$figwheel_cljs_repl_STAR_.invokeStatic(system.clj:584)
	at figwheel_sidecar.system$figwheel_cljs_repl_STAR_.invoke(system.clj:582)
	at figwheel_sidecar.system$build_switching_cljs_repl_STAR_.invokeStatic(system.clj:590)
	at figwheel_sidecar.system$build_switching_cljs_repl_STAR_.invoke(system.clj:586)
	at figwheel_sidecar.system$cljs_repl_STAR_.invokeStatic(system.clj:606)
	at figwheel_sidecar.system$cljs_repl_STAR_.invoke(system.clj:597)
	at figwheel_sidecar.system$start_repl.invokeStatic(system.clj:631)
	at figwheel_sidecar.system$start_repl.invoke(system.clj:625)
	at figwheel_sidecar.system$start_repl.invokeStatic(system.clj:629)
	at figwheel_sidecar.system$start_repl.invoke(system.clj:625)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$apply.invoke(core.clj:652)
	at figwheel_sidecar.system$cljs_repl.invokeStatic(system.clj:639)
	at figwheel_sidecar.system$cljs_repl.doInvoke(system.clj:637)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at figwheel_sidecar.repl_api$start_figwheel_from_lein.invokeStatic(repl_api.clj:156)
	at figwheel_sidecar.repl_api$start_figwheel_from_lein.invoke(repl_api.clj:147)
	at figwheel_sidecar.repl_api$launch_from_lein.invokeStatic(repl_api.clj:224)
	at figwheel_sidecar.repl_api$launch_from_lein.invoke(repl_api.clj:216)
	at user$eval21371.invokeStatic(form-init840872489928647865.clj:1)
	at user$eval21371.invoke(form-init840872489928647865.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7062)
	at clojure.lang.Compiler.eval(Compiler.java:7052)
	at clojure.lang.Compiler.load(Compiler.java:7514)
	at clojure.lang.Compiler.loadFile(Compiler.java:7452)
	at clojure.main$load_script.invokeStatic(main.clj:278)
	at clojure.main$init_opt.invokeStatic(main.clj:280)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invokeStatic(main.clj:311)
	at clojure.main$null_opt.invokeStatic(main.clj:345)
	at clojure.main$null_opt.invoke(main.clj:342)
	at clojure.main$main.invokeStatic(main.clj:424)
	at clojure.main$main.doInvoke(main.clj:387)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.main.main(main.java:37)
Caused by: java.lang.Exception: No namespace: figwheel4node-server.core found
	at clojure.core$the_ns.invokeStatic(core.clj:4128)
	at clojure.core$ns_name.invokeStatic(core.clj:4130)
	at clojure.core$ns_name.invoke(core.clj:4130)
	at clojure.tools.reader$read_namespaced_map.invokeStatic(reader.clj:760)
	at clojure.tools.reader$read_namespaced_map.invoke(reader.clj:752)
	at clojure.tools.reader$read_dispatch.invokeStatic(reader.clj:71)
	at clojure.tools.reader$read_dispatch.invoke(reader.clj:67)
	at clojure.tools.reader$read_STAR_$fn__1150.invoke(reader.clj:924)
	at clojure.tools.reader.reader_types$log_source_STAR_$fn__796.invoke(reader_types.clj:293)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:657)
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1965)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1965)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojure.tools.reader.reader_types$log_source_STAR_.invokeStatic(reader_types.clj:292)
	at clojure.tools.reader.reader_types$log_source_STAR_.invoke(reader_types.clj:287)
	at clojure.tools.reader$read_STAR_.invokeStatic(reader.clj:914)
	... 64 more
:a
1
clojure.lang.ExceptionInfo: <NO_SOURCE_FILE> [line 1, col 2] Unmatched delimiter }. {:type :reader-exception, :ex-kind :reader-error, :file "<NO_SOURCE_FILE>", :line 1, :col 2}
	at clojure.core$ex_info.invokeStatic(core.clj:4739)
	at clojure.core$ex_info.invoke(core.clj:4739)
	at clojure.tools.reader.impl.errors$throw_ex.invokeStatic(errors.clj:34)
	at clojure.tools.reader.impl.errors$throw_ex.doInvoke(errors.clj:24)
	at clojure.lang.RestFn.invoke(RestFn.java:442)
	at clojure.tools.reader.impl.errors$reader_error.invokeStatic(errors.clj:40)
	at clojure.tools.reader.impl.errors$reader_error.doInvoke(errors.clj:36)
	at clojure.lang.RestFn.invoke(RestFn.java:460)
	at clojure.tools.reader.impl.errors$throw_unmatch_delimiter.invokeStatic(errors.clj:112)
	at clojure.tools.reader.impl.errors$throw_unmatch_delimiter.invoke(errors.clj:111)
	at clojure.tools.reader$read_unmatched_delimiter.invokeStatic(reader.clj:77)
	at clojure.tools.reader$read_unmatched_delimiter.invoke(reader.clj:75)
	at clojure.tools.reader$read_STAR_$fn__1150.invoke(reader.clj:924)
	at clojure.tools.reader.reader_types$log_source_STAR_$fn__796.invoke(reader_types.clj:293)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:657)
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1965)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1965)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojure.tools.reader.reader_types$log_source_STAR_.invokeStatic(reader_types.clj:292)
	at clojure.tools.reader.reader_types$log_source_STAR_.invoke(reader_types.clj:287)
	at clojure.tools.reader$read_STAR_.invokeStatic(reader.clj:914)
	at clojure.tools.reader$read_STAR_.invoke(reader.clj:906)
	at clojure.tools.reader$read.invokeStatic(reader.clj:977)
	at clojure.tools.reader$read.invoke(reader.clj:950)
	at cljs.repl$repl_read.invokeStatic(repl.cljc:106)
	at cljs.repl$repl_read.invoke(repl.cljc:85)
	at cljs.repl$repl_read.invokeStatic(repl.cljc:97)
	at cljs.repl$repl_read.invoke(repl.cljc:85)
	at rebel_readline.core$create_buffered_repl_reader_fn$fn__26483$fn__26484.invoke(core.clj:175)
	at cljs.repl$repl_STAR_$read_eval_print__6536$fn__6537.invoke(repl.cljc:949)
	at cljs.repl$repl_STAR_$read_eval_print__6536.invoke(repl.cljc:942)
	at cljs.repl$repl_STAR_$fn__6542$fn__6551.invoke(repl.cljc:998)
	at cljs.repl$repl_STAR_$fn__6542.invoke(repl.cljc:997)
	at cljs.compiler$with_core_cljs.invokeStatic(compiler.cljc:1285)
	at cljs.compiler$with_core_cljs.invoke(compiler.cljc:1274)
	at cljs.repl$repl_STAR_.invokeStatic(repl.cljc:960)
	at cljs.repl$repl_STAR_.invoke(repl.cljc:839)
	at rebel_readline.cljs.repl$repl_STAR_.invokeStatic(repl.clj:72)
	at rebel_readline.cljs.repl$repl_STAR_.invoke(repl.clj:61)
	at clojure.lang.Var.invoke(Var.java:385)
	at figwheel_sidecar.repl$eval19824$fn__19825.invoke(repl.clj:218)
	at clojure.lang.MultiFn.invoke(MultiFn.java:233)
	at figwheel_sidecar.repl$repl.invokeStatic(repl.clj:344)
	at figwheel_sidecar.repl$repl.doInvoke(repl.clj:342)
	at clojure.lang.RestFn.invoke(RestFn.java:436)
	at figwheel_sidecar.system$start_figwheel_repl.invokeStatic(system.clj:520)
	at figwheel_sidecar.system$start_figwheel_repl.invoke(system.clj:511)
	at figwheel_sidecar.system$figwheel_cljs_repl_STAR_.invokeStatic(system.clj:584)
	at figwheel_sidecar.system$figwheel_cljs_repl_STAR_.invoke(system.clj:582)
	at figwheel_sidecar.system$build_switching_cljs_repl_STAR_.invokeStatic(system.clj:590)
	at figwheel_sidecar.system$build_switching_cljs_repl_STAR_.invoke(system.clj:586)
	at figwheel_sidecar.system$cljs_repl_STAR_.invokeStatic(system.clj:606)
	at figwheel_sidecar.system$cljs_repl_STAR_.invoke(system.clj:597)
	at figwheel_sidecar.system$start_repl.invokeStatic(system.clj:631)
	at figwheel_sidecar.system$start_repl.invoke(system.clj:625)
	at figwheel_sidecar.system$start_repl.invokeStatic(system.clj:629)
	at figwheel_sidecar.system$start_repl.invoke(system.clj:625)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$apply.invoke(core.clj:652)
	at figwheel_sidecar.system$cljs_repl.invokeStatic(system.clj:639)
	at figwheel_sidecar.system$cljs_repl.doInvoke(system.clj:637)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at figwheel_sidecar.repl_api$start_figwheel_from_lein.invokeStatic(repl_api.clj:156)
	at figwheel_sidecar.repl_api$start_figwheel_from_lein.invoke(repl_api.clj:147)
	at figwheel_sidecar.repl_api$launch_from_lein.invokeStatic(repl_api.clj:224)
	at figwheel_sidecar.repl_api$launch_from_lein.invoke(repl_api.clj:216)
	at user$eval21371.invokeStatic(form-init840872489928647865.clj:1)
	at user$eval21371.invoke(form-init840872489928647865.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7062)
	at clojure.lang.Compiler.eval(Compiler.java:7052)
	at clojure.lang.Compiler.load(Compiler.java:7514)
	at clojure.lang.Compiler.loadFile(Compiler.java:7452)
	at clojure.main$load_script.invokeStatic(main.clj:278)
	at clojure.main$init_opt.invokeStatic(main.clj:280)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invokeStatic(main.clj:311)
	at clojure.main$null_opt.invokeStatic(main.clj:345)
	at clojure.main$null_opt.invoke(main.clj:342)
	at clojure.main$main.invokeStatic(main.clj:424)
	at clojure.main$main.doInvoke(main.clj:387)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.main.main(main.java:37)
```

Repro (only with current `0.5.16-SNAPSHOT`, not `0.5.16`) is as follows. (Derived from https://github.com/bhauman/lein-figwheel/wiki/Node.js-development-with-figwheel, but simply modernizing the deps):

`project.clj`:

```clojure
(defproject figwheel4node "0.1.0-SNAPSHOT"
  :dependencies [[org.clojure/clojure "1.9.0"]
                 [org.clojure/clojurescript "1.10.238"]]
  :plugins [[lein-cljsbuild "1.1.7"]
            [lein-figwheel "0.5.16-SNAPSHOT"]]
  :clean-targets ^{:protect false} ["target"]
  :cljsbuild {
    :builds [{:id "server-dev"
              :source-paths ["server_src"]
              :figwheel true
              :compiler {:main figwheel4node-server.core
                         :output-to "target/server_out/figwheel4node_server_with_figwheel.js"
                         :output-dir "target/server_out"
                         :target :nodejs
                         :optimizations :none
                         :source-map true }}]}
  :figwheel {})
```

`server_src/figwheel4node_server/core.cljs`:

```clojure
(ns ^:figwheel-always figwheel4node-server.core
  (:require [cljs.nodejs :as nodejs]))
(nodejs/enable-util-print!)
(println "Hello from the Node!")
(def -main (fn [] nil))
(set! *main-cli-fn* -main) ;; this is required
```

Then in one terminal:

```
lein figwheel server-dev
```

and in another:

```
node target/server_out/figwheel4node_server_with_figwheel.js
```

Then issue the require and namespace map forms at the beginning of this issue.

**Comment by bhauman** [comment]
you mean `0.5.17-SNAPSHOT` ?

**Comment by mfikes** [comment]
Ahh, no. It is fine in that version. Closing as no issue.
