### ISSUE TITLE
cljsbuild with :notify-command makes lein figwheel <id> crash

### ISSUE THREAD

**Issue by petterik** [bhauman/lein-figwheel#72]
Given cljsbuild configuration with `:notify-command`, my `lein figwheel <build-id>` crashes with the following output:
```
java.lang.ClassCastException: java.lang.String cannot be cast to clojure.lang.IFn
	at user$eval12012.invoke(form-init8384330571696966499.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6767)
	at clojure.lang.Compiler.eval(Compiler.java:6757)
	at clojure.lang.Compiler.load(Compiler.java:7194)
	at clojure.lang.Compiler.loadFile(Compiler.java:7150)
	at clojure.main$load_script.invoke(main.clj:274)
	at clojure.main$init_opt.invoke(main.clj:279)
	at clojure.main$initialize.invoke(main.clj:307)
	at clojure.main$null_opt.invoke(main.clj:342)
	at clojure.main$main.doInvoke(main.clj:420)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Subprocess failed
```
When I leave out the `:notify-command` option, it works as expected.
It does not seem to matter what the value of the `:notify-command` option is. I tried `:notify-command ["x"]` and I get the same error.

Here's the whole cljsbuild part of my project.clj:
```cljs
  :cljsbuild {:builds [{:id "test"
                        :source-paths ["src" "test"]
                        :notify-command ["phantomjs" "phantom/unit-test.js" "phantom/unit-test.html"]
                        :compiler  {:output-to     "target/testable.js"
                                    :optimizations :whitespace
                                    :pretty-print  true}}
                       {:id "dev"
                        :source-paths ["src/cljs"]
                        :compiler {:output-to     "dev-resources/public/js/app.js"
                                   :output-dir    "dev-resources/public/js/out"
                                   :source-map    "dev-resources/public/js/out.js.map"
                                   :optimizations :none
                                   :cache-analysis true}}]}

```

**Comment by petterik** [comment]
Here are the version numbers from my project.clj:
```cljs
  :dependencies [[org.clojure/clojure "1.7.0-alpha5"]
                 [org.clojure/clojurescript "0.0-2665"]
                 [figwheel "0.2.2-SNAPSHOT"]
                 [org.clojure/test.check "0.7.0"]]

  :plugins [[lein-cljsbuild "1.0.4"]
            [lein-figwheel "0.2.2-SNAPSHOT"]]
```

**Comment by bhauman** [comment]
I just fixed this. Thanks for the report.

Refetch 0.2.2-SNAPSHOT and you should be good.

**Comment by petterik** [comment]
Yay! Verified in 0.2.2-SNAPSHOT
