### ISSUE TITLE
lein repl not working with current template

### ISSUE THREAD

**Issue by mikeThurmond** [bhauman/lein-figwheel#725]
I'm trying to run lein-repl with the current template and I get the following error:

``Error loading cider.nrepl.middleware.test: java.lang.RuntimeException: Invalid token: ::clojure.test/once-fixtures, compiling:(cider/nrepl/middleware/test.clj:98:57)
Exception in thread "main" java.lang.RuntimeException: Unable to resolve var: cider.nrepl.middleware.test/wrap-test in this context, compiling:(/private/var/folders/24/sdhf3sks1jl8b73928rbgz9r0000gn/T/form-init5757178205789070440.clj:1:5548)``

I have gone through the using this guide with no luck: https://github.com/bhauman/lein-figwheel/wiki/Using-the-Figwheel-REPL-within-NRepl

**Comment by zhaoyul** [comment]
which version of Leiningen are you using? @mikeThurmond

**Comment by victorb** [comment]
Having a similar problem with leiningen version 2.9.0

```
[WARNING] No nREPL middleware descriptor in metadata of #'cider.piggieback/wrap-cljs-repl, see nrepl.middleware/set-descriptor!
nREPL server started on port 39569 on host 127.0.0.1 - nrepl://127.0.0.1:39569
ERROR: Unhandled REPL handler exception processing message {:id cb494957-4a9f-4835-ada6-b0c978bed506, :op clone}
java.lang.NullPointerException
        at clojure.core$deref_future.invokeStatic(core.clj:2292)
        at clojure.core$deref.invokeStatic(core.clj:2312)
        at clojure.core$deref.invoke(core.clj:2298)
        at cider.piggieback$wrap_cljs_repl$fn__22753.invoke(piggieback.clj:222)
        at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__17873.invoke(middleware.clj:22)
        at nrepl.server$handle_STAR_.invokeStatic(server.clj:18)
        at nrepl.server$handle_STAR_.invoke(server.clj:15)
        at nrepl.server$handle$fn__22375.invoke(server.clj:27)
        at clojure.core$binding_conveyor_fn$fn__5476.invoke(core.clj:2022)
        at clojure.lang.AFn.call(AFn.java:18)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

Did a `lein new fighweel $dir`, `cd $dir` and then `lein repl` to get the error above.
