### ISSUE TITLE
Exception on Windows when opening page in browser

### ISSUE THREAD

**Issue by gphilipp** [bhauman/lein-figwheel#76]
Figwheel works ok on Mac but I have this exception on windows (both on personal and work computer) when I go to ```http://localhost:3449```in the browser. Not sure of the impact, still at early steps of discovering how figwheel works for me.

```
Prompt will show when figwheel connects to your application
To quit, type: :cljs/quit
java.lang.NullPointerException
        at sun.misc.MetaIndex.mayContain(Unknown Source)
        at sun.misc.URLClassPath$JarLoader.getResource(Unknown Source)
        at sun.misc.URLClassPath.getResource(Unknown Source)
        at sun.misc.URLClassPath.getResource(Unknown Source)
java.lang.NullPointerException
        at java.lang.ClassLoader.getBootstrapResource(Unknown Source)
        at java.lang.ClassLoader.getResource(Unknown Source)
        at java.lang.ClassLoader.getResource(Unknown Source)
        at clojure.java.io$resource.invoke(io.clj:441)
        at clojure.java.io$resource.invoke(io.clj:440)
ClojureScript:cljs.user>        at cljs.closure$source_for_namespace.invoke(closure.clj:487)
        at cljs.repl$load_namespace.invoke(repl.clj:57)
        at cljs.repl$load_dependencies.invoke(repl.clj:77)
        at cljs.repl$evaluate_form.invoke(repl.clj:130)
        at cljs.repl$repl_STAR_.invoke(repl.clj:284)
        at figwheel_sidecar.repl$repl.invoke(repl.clj:64)
        at figwheel_sidecar.auto_builder$autobuild_repl.invoke(auto_builder.clj:221)
        at figwheel_sidecar.auto_builder$run_autobuilder.invoke(auto_builder.clj:236)
        at user$eval12412.invoke(form-init1595373007279590366.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6703)
        at clojure.lang.Compiler.eval(Compiler.java:6693)
        at clojure.lang.Compiler.load(Compiler.java:7130)
        at clojure.lang.Compiler.loadFile(Compiler.java:7086)
        at clojure.main$load_script.invoke(main.clj:274)
        at clojure.main$init_opt.invoke(main.clj:279)
        at clojure.main$initialize.invoke(main.clj:307)
        at clojure.main$null_opt.invoke(main.clj:342)
        at clojure.main$main.doInvoke(main.clj:420)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at clojure.lang.Var.invoke(Var.java:383)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.Var.applyTo(Var.java:700)
        at clojure.main.main(main.java:37)
```

**Comment by mavbozo** [comment]
Same with me too. I use Windows 7. 

But the NPE only occurs once when starting `lein figwheel`. The cljs compilation and reloading still works. CSS reloading also works.

**Comment by swannodette** [comment]
@gphilipp that's another Windows bug in ClojureScript that has been fixed in master.

**Comment by gphilipp** [comment]
This one I guess ?
https://github.com/clojure/clojurescript/commit/80d46bdb7969c6a914324f1b9c81f8246d01f0a7

**Comment by swannodette** [comment]
@gphilipp just cut 0.0-2740, give it a try

**Comment by mavbozo** [comment]
Tested using 0.0-2740 and the exception gone.

**Comment by gphilipp** [comment]
It fixed the issue for me as well, thx @swannodette !
