### ISSUE TITLE
will not update file changes on windows

### ISSUE THREAD

**Issue by ThomasDeutsch** [bhauman/lein-figwheel#85]
After i change the file, figwheel will try to load the new .js from this location: http://localhost:3449/resources/js/out/flappy_bird_demo/core.js?zx=zg5q0oi1q5w8

and i get a 404 - file not found exception.

The initial load of the script is fine - i only get 404s when i changed something.
I am using the flappy-bird-demo without modifications on a windows 7 machine.

**Comment by bhauman** [comment]
Are you loading the application from http://localhost:3449? Or the file system?

Also could you update to lein-figwheel 0.2.3-SNAPSHOT (in project.clj) and see if it works?

**Comment by bhauman** [comment]
By the way epic bike ride man! I hiked the Appalachian Trail back in the day :)

**Comment by ThomasDeutsch** [comment]
Thanks :)   That sounds like an amazing adventure.


I am loading the application from localhost:3449. I discovered that i get this NullPointerException when i start the build process with lein figwheel.

```
......
To quit, type: :cljs/quit
java.lang.NullPointerException
        at sun.misc.MetaIndex.mayContain(MetaIndex.java:243)
        at sun.misc.URLClassPath$JarLoader.getResource(URLClassPath.java:830)
        at sun.misc.URLClassPath.getResource(URLClassPath.java:199)
        at sun.misc.URLClassPath.getResource(URLClassPath.java:251)
        at java.lang.ClassLoader.getBootstrapResource(ClassLoader.java:1305)
        at java.lang.ClassLoader.getResource(ClassLoader.java:1144)
java.lang.NullPointerException
        at java.lang.ClassLoader.getResource(ClassLoader.java:1142)
        at clojure.java.io$resource.invoke(io.clj:441)
        at clojure.java.io$resource.invoke(io.clj:440)
        at cljs.closure$source_for_namespace.invoke(closure.clj:487)
        at cljs.repl$load_namespace.invoke(repl.clj:57)
        at cljs.repl$load_dependencies.invoke(repl.clj:77)
        at cljs.repl$evaluate_form.invoke(repl.clj:130)
        at cljs.repl$repl_STAR_.invoke(repl.clj:284)
        at figwheel_sidecar.repl$repl.invoke(repl.clj:64)
        at figwheel_sidecar.auto_builder$autobuild_repl.invoke(auto_builder.clj:
217)
        at figwheel_sidecar.auto_builder$run_autobuilder.invoke(auto_builder.clj
:232)
        at user$eval12418.invoke(form-init4847066405857012685.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6703)
        at clojure.lang.Compiler.eval(Compiler.java:6693)
        at clojure.lang.Compiler.load(Compiler.java:7130)
        at clojure.lang.Compiler.loadFile(Compiler.java:7086)
        at clojure.main$load_script.invoke(main.clj:274)
        at clojure.main$init_opt.invoke(main.clj:279)
        at clojure.mainClojureScript:cljs.user> $initialize.invoke(main.clj:307)

        at clojure.main$null_opt.invoke(main.clj:342)
        at clojure.main$main.doInvoke(main.clj:420)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at clojure.lang.Var.invoke(Var.java:383)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.Var.applyTo(Var.java:700)
        at clojure.main.main(main.java:37)
```

**Comment by bhauman** [comment]
Ah you will need to update clojurescript to its latest release

[org.clojure/clojurescript "0.0-2760"]

in the project.clj

If that works let me know and I'll fix the repo.

**Comment by ThomasDeutsch** [comment]
You are correct about the Exception. It is gone with clojurescript 0.0-2760. Sadly, i still can not access the updated .js files from localhost:3449

![screenshot chrome](https://i.imgur.com/Zgcz4Sx.png "Firefox shows same behavior")

**Comment by ThomasDeutsch** [comment]
i have figured out hat i have not updated the line-figwheel in :plugins
Now, it works as expected.
