### ISSUE TITLE
Unresolved symbol `transitive-dependencies`

### ISSUE THREAD

**Issue by sfnelson** [bhauman/lein-figwheel#94]
https://github.com/bhauman/lein-figwheel/blob/master/sidecar/src/figwheel_sidecar/core.clj#L309

```
Exception in thread "main" java.lang.RuntimeException: Unable to resolve symbol: transitive-dependents in this context, compiling:(figwheel_sidecar/core.clj:308:38)
...
	at figwheel_sidecar.repl$eval65$loading__4958__auto____66.invoke(repl.clj:1)
	at figwheel_sidecar.repl$eval65.invoke(repl.clj:1)
```

**Comment by bhauman** [comment]
Its fixed and deployed sorry about this.
